### ISSUE TITLE
Idempotency problem when no space between getter and parameter

### ISSUE THREAD

**Issue by lkluc** [fsprojects/fantomas#2291] opened 2022-06-06 16:00 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYgM4CCRALgKIAeAhugA54A6ATswHZufkCeD%2BAJYdyiVh1o5CsWAAoAlGAC83DhAjpE6AEZiw5ABaCiAOgDmicmFk4UwqzmPlFSsABYATKtV8BYe2ISUgBCtKwKyqrqYJo6eobGJtphEa4ciADu0nLyUeqxuqz6RqbJ4YLw1ACMADT%2BlR4uxYllCuaWANoV1QDc9dQeALqQNeBQRJbkwmZEqGAdYxCg0RCQACS%2ByGiQ9iOL6usAbpJYW-P70QAMoysHAJIcSCIAyoIAXsg3t%2B4XYIP7AF8vktfutNnMdiI9rcjiczgtvmBar9VgBZWjUAAywkQmMQHDMhmh3yqHkuv3%2B0SB%2B2WKzB-DOkHx8AA8gAzbHpZ58PDE6KwnCnOYI74eYF0yiPdmcz4oqA4NmQCmA8W0-kbBkQ7QyHB8g5rY6C%2BFygDM4v5DwmrHIBGEkgAcplHOk9dFyKxTsqqarQRqBFqda6oAa4cK5W5zQdngxaNBEMFEGzYKxEAAFML0SxiIMQd2e26U9TU6Jq-Xg7ba2C6yMCoVoEW3ACskdW0dj8cTydxsAyYmgtAmD0OsH7U1gHBz%2Bg9iC9RZ9ML9jMr1d9hrr50RADYW1A23GE0mUwBVBgCVj9wccYejwTjydsyQTWcQYvqUurRcBqtB2vGxEAdh3SA9w7Q9EAAYRwAciHA8cKA9aByGTe9HxnAsVRpX1yygZcfxDI0w0RAAOICQIPLtUS0QoUJwJ90O9TCF2wyBcJrfD1wbFYAE5SJjfdOxTWCcDvHcH1otCVkLF95zpT8K0DNi1z-ElrjlYC%2BMQEg2VEVhYPQdBaEnPMJOiKSwFfEEmM1eTv0U0N6zlKpkURdT23IlNni0QQ4GEidRNQ59zJk9VmNY1d7I3EkxTUkCtJ0zz0G8qsRLlYzAossB32DUKFPCgiHMRKozRijSSFYWAsEeAARRBHESnSjOndLgrLayoF2Oz8si24qgjNT0WoO42QAFQMfFKHE54DGTcgAHUKiJHc3HJei50Y2TmI6vKOMc5t%2BoxB42UEagWTPWgkNYGgGBTIgiFvPy5UbFbJIwkssLayFyDwpTCJJbd9uoAAlRA4FYeB5vgRbw2e0zXrfd7-W2LaFx%2BgqSUAgHgdB%2BB7SwOJWHZO5RHQWYdyqZr1pCj70FwKZnUQAhkwM8gdOGzVOp2wqSLUrHk3gVFacEenGdYZmGqA6ADAzRCxAAfQyBaDCVVbpMp1rEfaqEOeUnqeIBsrWFoXgWVYbEKAhqHEWWim3qsjXPu%2BiLOOiMkgIGg2jZNs3yFx-HCeJ0nHJt%2BG7cZGmcDpnERbFsQ2f9bXftuDxnO%2BSAPeN02nAFiOhajpnzvFtTJelnT5cV5WXoY22No%2B5HZNR7qVg8aKXIGgA1OFgmEeBpgtpWdyImH1DMjKsvpe26-VBvnfUDxitbjECEqxD7q7x5e-Lpah4gEeWo-Tate2nWm76hfqCq2ByAAcUsK6bru8c%2B8nJ7g8smv7bClGnblDw9tbwX6bBGEtAAA1sEQ2oDLBEBZBwZ4mYhJ4weoiMSdFK5rWrlTD%2BuUv5dRnhADw-0XKOgyIAywvZ8Rx0QDVI6HBBBjg4CQR4lF8aB2QQFFWQU1b7w%2Bp-eu39EQeAxi5EgjgzAcCXhwFe45XhiPOlgFMw1YAPCeOQc690aKoNhlXEO78lzYL4bgn%2B3NhER0CGow43YCTMMKNQ4QdD7qsO%2BCgkyw84Zv0wXo2yR9E5Nz1v-HOMpMT0G0PAWgkFYB3QJMQ%2BmGiXE7zcZlBGniVw4M5t8E0qkXJXTEIITQIhJAAGlECIAYMo-E5AHjgNoJI-ucpnGv0SaHL8KSDFpNuCaFOMIgHVJATKUg5VKo40QBQRA-MAE4jvsMh%2BHBHG3DShw0eSTmmO0MYiE0LdU6hFYO5KhxhoCsFyXaUQ8Ajy0PHDVaAUFDb0NiQ0seckcL6Knvw9J89U7ZIOXk1ROBuQDPglgBg3JeC8n8uJO5SykaH1ScfaIJpT6pyKSUgavtCjsm6RwXpOJZkrCqJcbefwEn3Jyl46FPjYV-1Tr87y5BUQIFlGwsFCyxiDC%2BDsIgxBBBzHqQCIAA)

#### Formatted code

```fsharp
module FsAstExample

type internal Foo() =
    member this.get(l: int list) = 42

type internal Bar() =
    member this.bar() = new Foo()

    member this.bar(idx1, idx2) =
        this.bar().get[idx1
        idx2]

```
            

#### Reformatted code

```fsharp
module FsAstExample

type internal Foo() =
    member this.get(l: int list) = 42

type internal Bar() =
    member this.bar() = new Foo()

    member this.bar(idx1, idx2) = this.bar().get[idx1 idx2]

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

I stumble upon this problem when trying to generate code with FsAst, I simplified the code to show the problem. 

Now I don't know if Visual Studio is too permissive, but it accepts when the code is specified without the space :
"this.bar().get[idx1; idx2]"

after Fantomas reformat, the list is split in two lines without the appropriate indentation, and it seems the first parameter is inferred as a ('a -> int) type... 

#### Options

Fantomas master branch at 2022-05-30T18:11:41Z - 5e927521516445116087af12c76d83e0dec01332

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment] 2022-06-07 06:12
Hello, thank you for reporting this issue.
This is a duplicate of https://github.com/fsprojects/fantomas/issues/2242.
Please read that thread to discover the relevance of that space.
I've added a hint [here](https://github.com/fsprojects/fantomas/issues/2158#issuecomment-1078725550) to solve this, are you interested in submitting a PR?

**Comment by lkluc** [comment] 2022-06-07 12:40
Hello Florian, thanks for the prompt reply! :)

I have unfortunately no fix for this problem. I'm currently working on a code generating project and I thought I was missing important part in my generated AST, and came to the conclusion after some comparative tests that Ranges are involved and would be necessary (not only dummy range0) to generate the appropriate code. 

After 2-3 days fighting this problem, I finally thought about a simple workaround, and blame myself under a huge pile of rocks of shame for not having thought about it earlier : parenthesis around the list! doh! 

Once I have finished with my code generation project, I might be able to push some improvement on the FsAst project though, but I have to figure out first if my workplace would allow it.

**Comment by lkluc** [comment] 2022-06-07 13:12
Yep, it crossed my mind to fake a +1 range just to see if it could work. But I thought it might been more contrived than this, in fact I was a bit surprised and discouraged at first to realize that ranges could be an important part of the AST tree, but when you think about it 2 seconds, I guess we could say that F# code have part of its semantic based on spaces, and relying on ranges might be unavoidable.

But yes, in deed, thanks for the code excerpt, it was on my TODO list eventually to look at Fantomas's interns, and I agree, it might do the trick! :)

**Comment by nojaf** [comment] 2022-06-07 13:22
Yes, a part of me also wished that we had a separate `SynExpr` case for the new indexer syntax without a dot. I'm not entirely sure what the rationale is there.

When it comes to code generation in general, you really need to follow as closely as possible what the parser produces. That is the tree that Fantomas can format, any deviation might not end well.

**Comment by lkluc** [comment] 2022-06-16 12:51
Hello nojaf,

> Where I'm wondering what
> (...)
> would return if both ranges are range0. Maybe faking one of the ranges, so that it is further away might resolve your problem.

   Yup, that did the trick, as you expected with a simple range of +1 :
``` F#
let range0 = Range.range0
let pos1 = Position.mkPos 0 1
let range1 = Range.mkRange range0.FileName pos1 pos1
```

Thanks!

**Comment by nojaf** [comment] 2022-06-21 05:47
Alright, I'll close this issue as there are many duplicates of this one already.

**Closed by nojaf** 2022-06-21 05:47 UTC
Labels: bug (soundness)
