### ISSUE TITLE
Bug report from fantomas-ui

### ISSUE THREAD

**Issue by vivainio** [fsprojects/fantomas#736] opened 2020-03-27 20:44 UTC
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=CoQwTg5gpgLgBAWQHTAPaoDYGc4AoBmArgHZwD6cAtAHwCwAUHE3AIQtwACARGplgDq9sSLBmJc4AH2pwwUAEaEAlhgAmASgYMgA)

Please describe here fantomas problem you encountered

#### Code

```fsharp
Target M.Tools (fun _ ->
    !! @"Tools\Tools.sln" |> rebuild)


```
            

#### Result

```fsharp
Target M.Tools (fun _ -> !!@"Tools\Tools.sln" |> rebuild)

```
            
#### Options

Fantomas Next - 3.3.0-3/26/2020

| Name | Value |
| ---- | ----- |
| `IndentOnTryWith` | `false` |
| `IndentSpaceNum` | `4` |
| `KeepNewlineAfter` | `false` |
| `MaxIfThenElseShortWidth` | `40` |
| `PageWidth` | `120` |
| `ReorderOpenDeclaration` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `SpaceAroundDelimiter` | `true` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment] 2020-03-28 10:22
@vivainio good news: I have a fix for this.
Bad news: it is part of the refactoring branch and it might take us a while before we release the next version, as it will be a major release.

**Comment by knocte** [comment] 2020-03-31 08:38
Is this bug a duplicate of https://github.com/fsprojects/fantomas/issues/488 ?

**Comment by vivainio** [comment] 2020-03-31 18:11
> Is this bug a duplicate of https://github.com/fsprojects/fantomas/issues/488 ?

No, there is no need to split lines. It's as if fantomas does not understand @".." strings

**Closed** 2020-04-13 19:38 UTC
