### ISSUE TITLE
Broken comma in match expression in parameter invocation 

### ISSUE THREAD

**Issue by piaste** [fsprojects/fantomas#1869] opened 2021-08-16 09:16 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAqgC4CWOAzgDoBOlAdjfUQJ4AO%2BBYAvGAIJiwAZmBJ0iYAD5gAQgOHki1UQHNGDWmLb4AwgAoAlNzBqIEdInQAjRNTBEAFiXIA6ALJhdAQzBpRRADRglj5gCkp0yoY8BmpqeOLCBkYmpvFgWEb8AAwpEPCwYHr6brq5pmaeRND26WAA7iQOZeUtUvwkYAC0AHwizS2mUrIA%2Bl29ORoDU-79FVU1GQ1Nk1OtfGCjPcaQlDsrq4MyoWOhZfqQ-uBQ5IhEpBHkqGAA2lcQoAOQACQs7E%2BQfgub1M3wAbp4cFhkGhXqsspdVpAAJJ0JBiADKJAAXsgEVMACzAiAAXWBAF88e8iVAflp-oDKSCvuDIdCXtSIABGRnlSCuTwADwAMqJEELEBEHEDVpyAExZamk8oU4EfFrfX5syCWWCwHDS9XMiFQp6wqaynkg9EWEhwHCwOi8IgAUVRAHlBCK6LiOWBBBCboryYy1bzaX80NrdfrLWDjWyzQMAMyWiCQdGsTzQRDSRCCWDURAABU81E85iINgNA0UUKDypD1I1dMjOr11aZLJNMN9%2BNTUAzWZzeYLYtgdRs0E8NxRoNgU9IDo75VriHrphV5VDTM1-zbMabRtZpt9AFZ%2B%2BnM9nc-nCwRWOxqFOZ3Q5wuSEv%2B-6KGuBkqN42nzhlq%2B7LjSXYJr6ABsF6DteI6FtoODTuQ2gOmEWDQEQBZgRA36Bn%2Bwaqoeu6ttGYFxseParAA7LBV7DreiCuBY1jULhfoBr%2BLT-hAm6mNuabAXu5Gxke3bsqsAAc9FDjeo5ofadAcfh3HlLxYD8VSQGkVAoFiRBJ6rAAnLJ2a8IIlbUGh6DoJ4HGruufGAYaulRu2BnxkZUycvCvqXnJCGINa6C2nqn6%2BqpTmaS5YZufph6GdRPncv5cGIBZVkhWFSkOdQdaEQ2xE6S2emiYlXnJQMcoXiiaJEG6dAACrUMwADqjT2CpXHRVpYCCTS8XlUBSWST5KZpQxvDULAWCogAIogOAkKFVl5QVPFEVuJGlQCYgUeJkEyn2-n8gKSKCE19gSs6P7ovYBZEB18BSv2%2BIKoVAHFa5u0MhVVFjdV56nYKKKCCQApuo%2BlQFs6AqsIW5DkB%2Byn9qeH2bUV20lRGUB-SNlWAy0nIwSDAoAEqIHA1DwM9r29hj6lbQJO243tRAHaNibE3RZOU9T8AAHJYFYNgekilboI8-acr1sU7rt6C4KQy3egAYgWdl3DYTV0p5APc%2BUnIyf5-MFvArjK2Qooa9QWtrRe1SllmVnDA0L1dXL31xb9%2B36xJhumJyplk9NZbMG61AigodNdW9jOmBpfUDc2bP44aXO%2BvKF5nWHngR1HThEMLovUOLkvS76sufc53sK2zSs4CrNua5UVm638-tHeaqWInnBfR0QltN9b6ut9r7GO-YztYTYbskB7kBe9jP1p37-0B1nFpkwAavG0iiPAKixxx73LyzONaunYaZ6ssoTYiZ1q3NWEowfqLHwv9OrGfNcxXXQk3LX07ITQOEBZQnUfoKeasAiAAHFbhwwRogJGKMT5owTiSZm2lV4gWGhnUBWdgaPytqrHM9poAAGtpBliobccgjV0TlkQIpEWqNIo9T-snVmeCPIb27gMWUpNESC0QHUMhuYiATglB3RAi1wZ0EaCjXgqIWKl0rqsKKXD5aAN2glAmBss680RAAaUQIgVgF0roShREw8wXofSaM4ZjL6K8fZrw5l3bygiTZQIFLdUK5B7DoIZufHB7jeEHgMZvO%2BIdESYgiHgaaygRYSieogSwrgECOKmFolxtc3H10iZzQhqwkx%2BT7stZQdBn50Ffg6TE1TKhYELE1WAdU0mVBRt1H8YT%2Bo8JEnw6JAiWhJl7lMSAvAm42DoF00EY4IhqLYvI0QSj0I9IIvk-%2BhTdFs30QQwxZTt4kJHg4oU5ZLDwE8EhWAyMIiiPEaKDZalE7YP6ZfQZUSDkxKmEmB%2BEz5pOE8JYPAASnD2HRMwMQgpnl9JTsJSMEp4AegceiFgeASmHN%2BZAiZrpkWeieY7agOBBBL20QAwaej8E31Kb84hEyzEWI6WIFENDPB1Ljhw3p5KdmUr2dSkBWLkzCImdIZCdBKEOPINNWaqJREKEQBbUhookGI2Rus-sjkeUX1wZ8zFPzkzGNFaWeShZAXkGgEoUKszKzwAIIoh0i1oDITLIudhTjuVbO4R8siQzvkjPKEmXxEy0VKCwlkpAsKuFXGJHiAE5A1bIyeFFMkQA)

#### Code

```fsharp
module Utils

type U = A of int | B of string

type C() = 
    member this.M (a : int, b : string) = ()

let f () = 
    let u = A 0
    do C().M(
        match u with
             | A i -> i
             | B _ -> 0
             ,
        match u with
             | A _ -> ""
             | B s -> s
    )
```
            

#### Result

```fsharp
module Utils

type U =
    | A of int
    | B of string

type C() =
    member this.M(a: int, b: string) = ()

let f () =
    let u = A 0

    do
        C()
            .M(
                match u with
                | A i -> i
                | B _ -> 0,
                match u with
                | A _ -> ""
                | B s -> s
            )

```
            
#### Problem description

When using a match expression as a parameter argument, the comma that separates parameters can be misinterpreted by the F# compiler as a tuple separator.

Options for disambiguating include:
  - Wrapping the match expression in parenthesis
  - Adding a newline after the match expression (as shown in the pre-format code)

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 08/11/2021 17:06:14 - 383b729f46ebc01dde282967c68337d5ad55fa17

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment] 2021-08-21 12:10
This is quite the horrible code you have there. I would advise against passing match expressions as arguments.
That being said I would accept a PR that extends the check we have in

https://github.com/fsprojects/fantomas/blob/a80f888cbb71e8d0bd65d05c6ceccf9502d30f69/src/Fantomas/CodePrinter.fs#L916-L950

so that in this case, the comma is also flipped.

**Comment by wuzzeb** [comment] 2021-11-22 19:43
I think I also hit this issue but with function matching.

Old Code

```fsharp
module Util

open Aether

let inline non<'a when 'a : equality> (def : 'a) : Lens<'a option, 'a> =
  ( function
      | Some(a) -> a
      | None -> def
  , fun a _ -> if a = def then None else Some(a)
  )
```

Note that [Aether](https://github.com/xyncro/aether)'s lens is a tuple of getter and setter so are defining a tuple of functions.

Result of formatting

```fsharp
let inline non<'a when 'a: equality> (def: 'a) : Lens<'a option, 'a> =
  (function
  | Some (a) -> a
  | None -> def, (fun a _ -> if a = def then None else Some(a)))
```

With the formatting, the F# compiler complains `error FS0002: This function takes too many arguments, or is used in a context where a function is not expected`

I worked around it by putting parens around the getter function, so fantomas formats it to

```fsharp
let inline non<'a when 'a: equality> (def: 'a) : Lens<'a option, 'a> =
  ((function
   | Some (a) -> a
   | None -> def),
   (fun a _ -> if a = def then None else Some(a)))
```

Which compiles but is still somewhat confusing to read since you don't instantly notice the comma

**Comment by nojaf** [comment] 2022-09-19 06:08
I believe this issue is fixed.
A regression test could close this issue.

**Closed** 2022-10-08 15:42 UTC
Labels: bug (soundness), good first issue
