### ISSUE TITLE
Raw method names with `/` are formatted improperly

### ISSUE THREAD

**Issue by ForNeVeR** [fsprojects/fantomas#406] opened 2019-01-29 15:56 UTC
### Description

I have a method named ` ``/ operator combines paths`` `, and Fantomas breaks the code when formatting this method.

### Repro code

[Here it is](http://ratatosk.dynu.net/fantomas/#?code=NoHgYghgxgLgfAXQLACgA2BTGACABrgemwHsAHDAJwhmIuymIFsAjASwDsMBnbU6gCy74AFAEpsALmwBXdqxwBeVNhXZMOUgEZsC7AAUB2AEQQjy1et4AmHfsNHmZlKuwBBLl0owAdAFEAjtIQaMIGMPyhAt4AwkxsnMImRgA0xo6ioqla2ESkVqJAA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwi8XjhjlEMPA3QB7ADZ6IAQXiSoshUqIzUBoZrSYAQjBl7+J3tXxx4KmoaICgYMG4e-ADChsaB6k5hJjLwwjF4eKjxwaGYyam8Wjr6RhDZ5JCwCFIQACq8AJ6MrLb2jiAASjCesLxSyHAAIjDoBqi8qPAMcYR2DjnOMN56ONDDBgw6BeUhqrrwALJ6sK3zAL5AA).

**Comment by nojaf** [comment] 2019-01-29 21:04
`/ operator combines paths` is being mistaken for an infix operator in [(|OpNameFull|)](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/SourceParser.fs#L100).

Not sure if this should be fixed here or in [FCS](https://github.com/fsharp/FSharp.Compiler.Service/blob/79e77bbf75666d980ee105f3e305ba7803f834dd/src/fsharp/PrettyNaming.fs#L405). Perhaps this is not a bug on either side.

A workaround for you could be to just put another space before the `/`, like [this](http://ratatosk.dynu.net/fantomas/#?code=NoHgYghgxgLgfAXQLACgA2BTGACABr7AemwHsAHDAJwhhMuyhIFsAjASwDsMBnbMmgBbd8ACgCU2AFzYArhzY4AvKmyrsmHGQCM2RdgAKg7ACIIxlWo18ATLoNHjLcyjXYAgt25UYAOgCiAI4yEGgihjACYYI+AMLM7FwipsYANCZOYmJp2kQ2YkA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA).

**Closed** 2019-08-30 12:19 UTC
