### ISSUE TITLE
Long type arguments violates name-sensitive alignment (vanity alignment)

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#1827] opened 2021-07-14 08:17 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBnWBbRApTAdgDoBORBAPgHxj6wEB06iJAlgIYA2rAXogDylyEEcApgSidoTToALmwIBzIQRHqw7eEnhoxYVrrDzFSgNxgC7HLIWtlYCgF8w3eao0jJWWADdERvqGtqYWVjbGdg7Orqzyjk5UqpAANOAYiHJy9kroqGAA2ukQoJ6QACRyAJ4ADshokPZyqcUiFb5cAK71ha3qAAxpnhCQAJIESARyAMq8yEPDAEx9YAC6rU4LJSsV1XX5jVMtZeUdnN35RcNgAIxbGpAAsuwAHgAy9ohviMpyABbHYY3Rb9FbrdSbVqlB6VWo9SAAI1gsE4gPU7S6PSuS3u6OmiCwrDgnHoAEE5ABRCYAeQAZh8CPMVhBaVxmGCNvdoejYfsGkiUWi2qdMZdmWAAMy4trTGrsaCIABCiFpsEkAAV2CRrJkWEL1ApuhyIVydrz4QLUdKMecseKACzSkay%2BVKlVqr6wADuLGg0kQ418sD92Xo%2BpEhsQxpEkPU3OFewtyKtZrOFzQ2M8AFYnVAXQrlarJABVGp1Eh%2B5iB4PsUMEcMstlRzzgmOmk6Jg6W8M29O9a4ANlzkHzbqLiAAwpxpOgJ-QTJ1oHI1Q2wKzOOyW5yoWbO-zkz2RbaxdcAOzD0eFj2PAkIvW59ebjStiCx0S7uFdg-Wo99zMaAAOC85QLd1JDnEl6wfJto1fdsYT3KBux-NM7WuABOYDXVJWk5BYOcsCwdhV0jWCwDfbYO0-fdBRQ0UM3FG5BnFEcQLHD18UJYkw2gjdm2fbc4w-PkkO-VN6P7IE7hY0ccLwkhOKJFEePFUitxNHcqJExExJOVCTyBRZh3GSY5GpAgABUSCqAB1Vh-lXR9%2BPUF9yPgnlEJ02jxOPBjrhuKUZLY0kSFgToJgAEUQbhCXkkiSCNdS200hDqKgJpD30vygUdFjnheUZaQsv4fgpPjpj%2BNU5Ds%2BAHNze1QSSuCUo8tLDmaOjfMkzwbhzPLXnGWlWBealy1rNUKReGpJHQdBWBU64s0agSNKErT4Qyzq-0Yod%2BpeAAlRA4BIeAarqh1lpcwT33Wg5Np87b-PPPbDuO%2BAADlOiwO8SDpUY8KwPJcxuMiKLAeMRnNA4sE6Thsm4RkADE1SIrIWAsz8trQoEgJY161XgR5Yfhz5kZIVG4uHaA-i1eV5IAfS9QwHNB9yEza%2B69Ik-91BuTC9pC7UqmpEgPnkM6AXqy6RFcsGIagKGGk5mEsu6jQQWHfLBfYYXRbiORPu%2Blg-oBoHGNZlr2e0mG4dYBHEDJin0cxh7sc8RZpOuSBtd1sW5CJ237cd2tKZY6naaXFhGeZgELbW1LtOVnlVZ5kRFiMvaADVMUVex4ByCXVwauOboTjajixgz3cCr38sR8Kl3mghc4mAuY6L6WIFltnIc8pPhRT8VFly2vXgi2A5AAcUySbpsQWam8L3MlpLyiy6-byua61OIEWPra%2BJu3PkVEloAAa0VbVz8ydBzOmHUIK%2BqDxSc1fweEpNN5V7mh92r33sQF6e2yo5A%2Bh%2BBjOoUUhoEHsk3UkEwbxGxIGba4r8mpuUtr3NqyFXZV3Vs9L2ABpRAiAaiFWKj8cY98cAMiZKgmC6C5YfzuhXXB2V3a41Hi8MqhJ0B-CXhdN%2B8tdjYN0t-beQ9%2BZe1mMoTgiAQpKC%2Bj8aqiAESPAQHQ4YaCVrJXjq1bSOCt6PWGBKZiXtSTcCUAQeuBBG70FmFY2snRJAWVgCZZRtYm6OQYTo5qeirafxTEYt2GgJSe2GN7OGLArDZH8G8egShEE-SgfYWB85vF8SEcwmiQTxHGM8BKDOB9ba0LeNYBE8B2BTlgHNZQACgGfAyU%2BK6q1S76MCZlH%2B1wJQ1wiRFOI7AERyJ4XEP40wqhTFeE05yMtrpr3aQcH48A6S0OmNUORnSJHdJHhEqkyz6SNKpiQTgtJIBZNujkzZ%2BTQn7wicQ0h7ipjjEvuwWxksX4%2BJabotpASN65OTl0kxf8Ikn1eWfWh6AQphQmAA%2BQAQA4k0ZLPGac10m5jUr4jB-isEGLEQCrZJiCEgq1FeSQ-T0DQDYISGJARiwwPoFFaA05tR1mmec9elzK7sNCZwiJay2BLnUUgNljD0irAWI0dAiM5r5Ffk4IAA)

#### Code

```fsharp
someJson
|> Json.serialize<
     {| reason: string
        added: {| id: string; name: string |} list
        removed: {| id: string; name: string |} list |}>

```
            

#### Result

```fsharp
someJson
|> Json.serialize<{| reason: string
                     added: {| id: string; name: string |} list
                     removed: {| id: string; name: string |} list |}>

```
            
#### Problem description

Result violates the "avoid name-sensitive alignments" rule.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/07/2021 07:46:28 - 6f0df78847a1dbb3c87fa2e00c6390703905b7c1

```fsharp
    { config with
                IndentSize = 2 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment] 2022-01-28 15:28
Duplicate of https://github.com/fsprojects/fantomas/issues/2042

**Closed by nojaf** 2022-01-28 15:28 UTC
Labels: bug (stylistic)
