### ISSUE TITLE
Comment dropped in a multi-option match

### ISSUE THREAD

**Issue by pbiggar** [fsprojects/fantomas#1855] opened 2021-08-05 15:00 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbAhgF2gCzAA8wB3AS2zwB0A7AHzCskybAHo2wBnbMgGz5g8iAE6JaDJgCNWHMADUAggDkAkgGUAEgFF1ExjFYBaAHwHoTSABpwULomy8aAcy6owAbVsRQEP1AASbABPAAdkNEgyGmxrbz9IAIA3TD4AVwjPeP8ABht-f0hVGiQY9TIAL2R8gogAFmywAF14gF8an0bEkPD3KJi42sSU9MyvWogARg6CyABZTEIAGWjEJcQXSkGJyYAmHMaW-3b431mgsMzIKVhYPm3C5NSM93GJ3ZnC9UR0Mjg%2BWA0RTYbQlADyADMVjRqo0IBDUvZDm0ZmdHj0rjc7g8Ek9Rq84WAAMyfBLqUKYaCIABCiAhsDEAAVMCJMOgHKIcf5sCIMsjjqiuhdepEsfdScNnmNCXVSRBIOTKTS6Qy1rASKJoJh7MUkrAtbxAVy-Dy%2BbUjn4Tv40biMX0xcbJfi0G9agBWOVQRVU2n0sQAVVC4REWp1ND1BrIRs9CL4SPNKNOQrtotu4qFIxeLsJADZPQqKT6VWIAMJ8bVcEuAni86DYBnG%2BGIxD8y2CobCzFpx14rNZCZgADs%2Be9yr9iDmPyknJjzdbECtfht8s79u7Et70oHAA4R4Wx6qqwCaI2wLH4wULQv2%2BcU1AHRvM1uJgBOPdKxQQ7CiKvoLCn00WwTAUkw7O9rnXDMpQJAdJjyQkCyVX1VW%2BX5-mjQlzyAy9E2tZNLjXbFH2g7NYOmBDR0-b8RFQv47gwgdAPnMBF06MCCNTIioOdfsdg%2BBDilKbAwRoAAVERggAdQoPBTyw5jWLAZdAnAh9uL7V0CkmEkKP3RQRFgNISgAEUQPgyF%2BaiAN5bD-CvFib3RDioGiWJiJ4zT-EmWUEIWQhVAhUThBobQ40QdQ8AZbBpPgLZPTqA5gLbUDb2c-o3PU59akmD1fMWYoITIQgwWDHAGW0QhQjELguCjE9PTdRKcJAvD2JFFyBncjTCUmPM8sIAAlRA4BEeAYrimUmrs3Cl3w9r0p7J8YJ2Yd%2BqGkb4GUNJ0GnERIVUb90DcT1JgUxzbTS9A0j4XhzJhAAxBksEcURRIIrqsq03cEPWhl4Dma7btWR6RGeqz83wFlKWogB9chYtks6Uqc%2BbXMWkjeOyt9%2Bv01lgjBEQVh4cbZPiqa-HsxTlO6NK0Y%2B5ban2fM-NxzB8cJsgeC2nbRH2w7jp6pHWtS%2Barpu-hgaenBqLe3p6dI95yIHSBWfZonsAB8W7sQEGwZnBDIdZOtRDhsgEcgIXZraq46cyhmCl2fjlb8%2BQpWpaJ4GiZwSdPBLLbYkWbc6u2FcZnTncWe6jLrOr3ZKL2fbJ-2lLmoOMo7JbQ4dnyI8IYzYGwABxBwKqqxAarqxPCUa5PqdXTj0wzjHPL8XZcudwGJZhakAWgABrakjb7hwuBE9Q2UQI9tvqzC5yS69kYu%2Ba1KbjzCV2PrleURASG12lsA1DZZcQUzCpoCg6sUEpJx5kQBYHeT54cxeV1UyDV%2B6gddlW5WAGlEEQKEAKQUNjFHHuyaEsIH5z2aslYWKM07ozXl-b6udQq-C4HgKuA4-ZPypqnQijdziZ0xg7bGytyguD4IgfSzhtobGiogKQcwEBQImI-WBC94FLy7FxD%2Bn1-BEngsrRQ5lnA0CjjQGOgJyjiJwGkMQolYCCQYTgOqckYHTRalbQOhCkGfwmESJWEwVY3VEDQNRSQ1QuBvrtU%2B0QL7Vg0WFWuBCG76IEX4IkTsTGa14JApYbIpDwEwGWWAtUXDb13qsZxF4tFwJ0QgvR8tSGCPDiY4ynNMBSGoegzmeB1DBBiIsWJtkKYzQDkkyIGx4CQkgeoEI1CPH20ETnExoJalQhiRDEQfAIQWzwedV%2BaUV7EOboSIk7cTH-0ASomIxRB6YCkaTWeLjBkvxUiM9%2BYzkGGM3iYnuSy%2B6QK4PpQyJRt48EQP9Tu2tS7VVqk4z0TF1ncOGcvbZjwSEtwgESH%2BByWTITEJkrg0ARAWWiDga5-pz6AlMtAcsrJDQz2gWszhz83mbI%2BXwnZBjahElQSYhp4K6wsKQKUhStgmg1CiFwe6tV3DyVaEAA)

#### Code

```fsharp
match x with
| "a" // still here
| "b" // VANISHES
| "c" -> "c"
```
            

#### Result

```fsharp
match x with
| "a" // still here
| "b"
| "c" -> "c"

```
            
#### Problem description

Formatting this code drops a comment

#### Options

Fantomas Master at 08/04/2021 06:29:48 - 4bfd2581e8ef3a1f52e333e9d3a6a77ef33ab07f

Default Fantomas configuration

**Comment by knocte** [comment] 2021-08-06 04:06
I think this is a dupe of https://github.com/fsprojects/fantomas/issues/1677

**Comment by pbiggar** [comment] 2021-08-06 04:09
Yeah, looks like it.

**Comment by nojaf** [comment] 2021-08-10 19:02
@pbiggar would you like a patch release with this fix?

**Closed** 2021-08-10 19:02 UTC
Labels: bug (soundness)

**Comment by pbiggar** [comment] 2021-08-10 20:48
> @pbiggar would you like a patch release with this fix?

No thanks, this wasn't a major worry for us.
