### ISSUE TITLE
Idempotency problem when using set and spread syntax

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/fantomas#2392] opened 2022-07-28 14:14 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdAdlgNogLmJgK4C2iATgJbRgC8YAzgQNoDkADGwHTdsCcbALpgA1E1ZtRbANxg2AWlny%2BctomVsAosNwEwAdwAWVfIkYAHAIbRE9CfnYAaTSk3p0xDt8FqPX7yt3T28OeGCAgCYuIUgncChmfHwqTABzRlQwFgSIUAgCqAASfABPC2Q0SFT8ONyCyCKANyscYkrs%2BsKOeMLCyABJTCRMfABlKgAvZF6%2BiAAWLrAheoBfWbylxrKKrOrRurnGlraOnLmIAEYNvsgAWSsADwAZVMRnxHT8I0OLy%2BilitCut6vlbiVyh1IJ94AB5ABmr0wiDGZTwv36zVa7Sy5wukRu-S0wwRSJmSwgkBw8MggLWNzBmJ2UIARrBYDgMQ0sadcRSwABmQkNIbMCj4ABiqVaADlEAYcG8uYV8BR2nTgQythDdlU2RzlcUTji0Hi5vNhZSxtZbAAhRDw2AURAABSsFCs5DMFENEFV6rmQIKIMKjO5zL2%2Bs5wuO2LO-IArJaoNabIh7Y7nc9YAZKNArMwhk1YPmUrBML6wP7EBrg1qjjrWezo9rjfGLmAAGzJyCpu0Op2IACqFgqFHzhcwxdLVHLlfhrWYtYgIYKYcpjcjzcNsd5pv5AHYe330wPnQBhHAFxjn8uMf3QfBO%2BeLmuB%2Bmg7URvXbmM8k2dB2AAcx42qemaIHciCkCylAvjgS7vpqn4Nt%2BUBRju-7thc-CgWmGaDreOBzsmC4IW%2BfRBiu9bgmhkAYX%2BbZ8h2lw9PyvZgQAgvC3q3qQpBWJW1bLmAq6bKhkJbgajFxsxfzXOxJ4Ec6YzQTQHIkfyZGIZRH6hl%2Bkk-tJrayfuLEEopXE8ZQqmkOpxEVsmwlIXWKG0YZ6G-iZe6AX8QqWWmnEULAxDDAAIogip2d6QlqhRhRUaJNFMh5%2By1DJPlmn0lwWuxDyPAM8IACpGJ8YxGE6%2BAAOpUPA3yVhwIliWA67FHRNSYUxZl-EmeVPIVJWfFo5HlZVNV1T8yado1LnUW5KW6lAHUZQBWWFJc3Z9QVmDwlQjywmOVhPhQWiPBYzqMIws6OfyQEzbpyH6RJi1pZ1pm%2BXMlxHltABKiBwBQ8DjfVybzPdCV6WuBkvct3mrfylwgb9-1OvAMpkLBFAIgMZikJkyaXE1yXhqlpDEDgKSKsiEpOgJySUEVkkrdhn24exf0A-Adzk5Tbw0xQdMxT20BGO6NjegA%2BgYtX1UT80kzDBzM3JczRD2%2BVBR6pSwhQrz3sDk23eDBSJc1rXbKlsMNl1H19JECkdvcTya1Y2u61Q97ozBlDY7j%2BMI3LT3uS9ZMU1QVOIPzgsM0zcMs3bFmOy7bt6-g3NhxHUdHUL7Ei2Lj6UFLMs-IHUPPVCVvgjba0FJE-mO-lABqca2qk8CpGkBuVndpficHFdK3HKt27lDdPBKoWPtdrfDB3Xeg8bECm8TG7tYP1vvTXECRL1Y%2BPGFsD4AA4gQp3neYV3lvPRu9y10NNsZG%2BZfykSbQ3PPh28trEdAADWtoej-gQRgsJMBjE9IgIiZAbodm0vFE2kM%2B4LQfi2J%2B8MOyRG%2Bo7OUCov4EFzJ8RmFQIq7UwKYa6nFhhQW9hQf2HZnIPVckHZBUlUFV03i-JGSdFRpEwBPTAU9ywTF4UdYgzoiqwCGCMfAR1rrwR0hDR6Zd%2B6sLes-DBbNuHekwLIpo7xyxpGoZjEhqRyF3nkfApeiC77l1UcrbqcwBRsXfmHMkzxPQsngFYS8sArrpBwRHCxt9zabiMmwzE1d%2BQCgdhcSAZ9KBUHIKMVoABpRAiALBSM%2BPgIYACrACMNrA18wT752KHg4voApE6xO-vk3%2BZJGBBRCsMOU95EBcw-hHM%2BF1L6YDoRcBhiimHKJYWEtR6CLgCnrjU90ylEBhQ9tAagdkdFmHgEOMh5YIrQCvB6MsMCLhwJKbYsZ9jbaFAFKPWJ8TlnZNaKiYKxB7xqgsKiUo6JSLFNmkleWq9Lbr3YeoyZu9YlpIyflL2mMES1MwPUt4-TPreGOSo055TzkFAFG-WJDyaBpwQOSIp5EmoJCELMaojAJRXSyEc1YQA)

#### Formatted code

```fsharp
let numeric =
    set['0' .. '9']
    + set['+'
    '-'
    '.'
    'e'
    'E']

let whitespace =
    set[','
    ':'
    '\u0009'
    '\u000a'
    '\u000d'
    '\u0020']

```
            

#### Reformatted code

```fsharp
let numeric = set['0' .. '9'] + set['+' '-' '.' 'e' 'E']

let whitespace = set[',' ':' '\u0009' '\u000a' '\u000d' '\u0020']

```

This code is invalid because it is missing `;` separator.

Another problem with this code, is that it gives a compiler warning because there should be a space between `set` and the bracket `[`

> The syntax 'expr1[expr2]' is used for indexing. Consider adding a type annotation to enable indexing, or if calling a function add a space, e.g. 'expr1 [expr2]'
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

#### Extra information

- [ ] The formatted result breaks my code.
- [X] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-07-28T06:18:27Z - 9f5feffdaaa225113e5109ccc40a92e109a8b972

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment] 2022-07-29 06:21
Hello, this is a duplicate of https://github.com/fsprojects/fantomas/issues/2158.
In short, calling `set[expr]` is considered to be an indexer expression (like `foo[1]`) in the new F# 6 syntax.
You need to add a space in your code to tell the compiler this is a function application instead of an indexer expression. ([Example](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdAdlgNogLmJgK4C2iATgJbRgC8YAzgWANoDkADOwHQ-sBOdgF0wAaiYsOY9gG4w7ALRyF-ee0Qr2AURG4WAdwAWVfIkYAHAIbRE9SYQ4AaLSi3p0xTt6HqPX7yt3T29OeGCAgCZuYUgncChmfHwqTABzRlQ2BIhQCHyoABJ8AE8LZDRIVPw4nPzIQoA3KxxiCuyCgs54zvqASUwkTHwAZSoAL2Qe3rAAFjqIYTqAX2nchaLS8qyq4drehubW9tYNiABGNc7IAFkrAA8AGVTER8R0-CN9mfPojaWCqs6nlrsUyu1IO94AB5ABmz0wiBGpTw3wKhxabSypxmYEiV3R2kGcIRUzOUBwsMg-xWVxB6LB20qACNYLAcGj6k1MSdyQBmAn9TDMCj4ABiqRaADlEAYcC9OQV8BQ2jTAXSNg0thDWezFUUjli0DiZrNBRBICNrLYAEKIWGwCiIAAKVgoVnIZgo%2BogytVvQB%2BSBBXpXO1O11HMFGOO2PJAFZzVArTZEHaHU7HrADJRoFZmANGrA8ylYJgfWA-Yg1UGNQdGTq2VHNdzY8byQA2JOW61p%2B2OxAAVQs5QoeYLmCLJaoZYrsJazBrEGD%2BVDFobEab%2BpjRo6MwA7N2U7b%2B06AMI4fOMM9lxh%2B6D4R1zhfVgO04Et8MsrfR1u7k29AAHEevbpgONyIKQzKUM%2BOCLm%2B6ofvWX5QJG25-ryuICCBqZgee7Kzkm85wa%2BnSBsudagihkBob%2BhqYT83Tkj2qYAIKwl6N6kKQVgVlWS5gCu6zIeCm56nRPJxri5yXMxx59hmSKQTQBHlkRL4CUJYBrpsonfuJLb0VJPz4nJvbsV6IzKXAOCEeS-EIbWSFUXpqE-oZknttJApmWxFCwMQgwACKIPKpCmDBSYOWR74hp%2Brm7DUEltnuvTnGazF3PcfSwgAKkY7wjEYjr4AA6lQ8CfBWnCaZRDLUdU6FGV5PyJplDw5fl7zaCRRUleVlVfEmHY1Y5FHOfVCWNcl-7kucXbtdlmCwlQ9zQqOViPhQ2j3BYTqMIwM5qeSgGjTFiFxSJTJQNNHkpQBnTnIei0AEqIHAFDwANVVJrMZ0FORgl1WGU17DNDFpcBr3vY68BSmQ0EUHCfRmKQmRJuctUTSD12QKQxA4Ck8qImKjo8cklC5aJ4PGWl2HMW9H3wDcBNEy8pMUOTXoVjARhujYXoAPoGBVVVY5dLm47d9bNalnTRN2WWsRQ7olNCFDPHe31DSd-35IDWk6VqoNJXds24pEsm4rcDzK6r6ua-g8NQZQyOo%2Bjc3i6u8W4-jhNUMTiAc1zlPU2bEPy6Z1t21Yasa1Qd4s-7gfB5t3PdtAfPug%2BlDC6LXxe8JksQtLoKyw9BSRD51tZQAajyNqpPAqRpNrFanYX2k%2ByXYPh7T8sZTXDxioFD5HY3gwt23v164ssXe1dPemzLnly5XbVD-cQWwPgADiBA7Xt5iHWW0%2B653RsbvpzYr-d5KRAtNeswHLw2rZ0AANY2tnH8EIw0KYBGB6RAN5WikGOriYi8FzpOQlpNXGtE%2B4tV6JEZ61sZRylfgQHM7wqblBCitTApgjqsUGBBF2FAPa4migDeeRd4GNgMrfc2MxIhQ2jvKNImAR6YDHmWMYXDNrECdLlWAAwhj4E2kdWC0DaEXQXsXMSN8y6rwrvkSI9MOFekwFIxorwyxpHIYjAhqRiG3hkaRORsCFEMKUU1VR-ImJP39qSR4HpmTwCsBeWAh10gYMDhYi%2B3c7E02QZ0PkVsZiQEPpQKg5BhgtAANKIEQBYcR7x8ADG-lYXhOtIEaTGkDbG65qKIOYRHAofIo5RLfjkj%2BpJGDKwCoMGUd5EDM2foHQ%2B%2B0T7Cj4iqSx%2Bs6Fd0XiEpBa98h8mrjUt0eFEBBQTtAag4UdFmHgIOIhZYQrQEvO6UsECZhQMGXPeR9CcaMOUQycu-JB5RJicsjJLRkT%2BWIHeFUFhkQlFROpEiQTRmVFLlchxuI%2BQbyick1JWVnaIzhLUzA9SXhUMYrPMABtgYlISmUlRd8QWPyic8mg%2BAbgIDJPk35hTlgJGENMKojAxSHSyEckAywgA))

**Comment by nojaf** [comment] 2022-08-24 06:21
Fixed by https://github.com/fsprojects/fantomas/pull/2446

**Closed by nojaf** 2022-08-24 06:21 UTC
Labels: bug (soundness)
