### ISSUE TITLE
List indentation issue

### ISSUE THREAD

**Issue by halcwb** [fsprojects/fantomas#999] opened 2020-08-14 07:10 UTC
When I use the online tool  with the following code (cannot create an issue because of a too long url!):

```fsharp
let drawer =
    Mui.drawer [
        // drawer.open' props.IsOpen

        drawer.children 
            [
                Html.div [ prop.className classes.toolbar ]
                props.Items
                |> List.map (fun s ->
                    Mui.listItem 
                        [
                        listItem.button true
                        match state with
                        | Some t when t = s -> listItem.selected true
                        | _ -> listItem.selected false
                        prop.text s
                        prop.onClick (fun _ ->
                        s
                        |> MenuItemClick
                        |> dispatch) 
                        ])
                |> Mui.list 
            ] 
        ]

```

I get this list indentation with setting: fsharp_multiline_block_brackets_on_same_column=true:

```fsharp
let drawer =
    Mui.drawer
        [
            // drawer.open' props.IsOpen

            drawer.children [ Html.div [ prop.className classes.toolbar ]
                              props.Items
                              |> List.map (fun s ->
                                  Mui.listItem [ listItem.button true
                                                 match state with
                                                 | Some t when t = s -> listItem.selected true
                                                 | _ -> listItem.selected false
                                                 prop.text s
                                                 prop.onClick (fun _ -> s |> MenuItemClick |> dispatch) ])
                              |> Mui.list ]
        ]

```
So correct for the parent list but wrong for the child lists. When you uncomment the first item in the parent list you'll get:

```fsharp
let drawer =
    Mui.drawer [ drawer.open' props.IsOpen

                 drawer.children [ Html.div [ prop.className classes.toolbar ]
                                   props.Items
                                   |> List.map (fun s ->
                                       Mui.listItem [ listItem.button true
                                                      match state with
                                                      | Some t when t = s -> listItem.selected true
                                                      | _ -> listItem.selected false
                                                      prop.text s
                                                      prop.onClick (fun _ -> s |> MenuItemClick |> dispatch) ])
                                   |> Mui.list ] ]

```
So all of the lists, parent and child lists, doesn't adhere to the same column setting.

The problem is when you re-indent the above code this will result in errors, I always want list items to be on a 'tab column'.

**Comment by nojaf** [comment] 2020-08-14 09:13
Hey @halcwb, is this using https://github.com/cmeeren/Feliz.MaterialUI by any chance?

fsharp_multiline_block_brackets_on_same_column by design has no influence when an Elmish pattern is found.
So this is a bit of a grey area and perhaps needs could use some more documentation.

In short, when Fantomas detects an expression in the shape of `identifier arrayOrListArgument` it will format things differently to have better support for Elmish constructs. (See [document](https://github.com/fsprojects/fantomas/blob/master/docs/Formatting-Elmish-code.md) for some context).

So the expected result here is should be something like:
```fsharp
let drawer =
    Mui.drawer  [
                     // drawer.open' props.IsOpen

                     drawer.children [ Html.div [ prop.className classes.toolbar ]
                                                        ... ]   ]
```

The bug here is that the `Mui.drawer [ singleElement ]` is not recognized as an elmish expression. So it takes the `fsharp_multiline_block_brackets_on_same_column` style there.

Unrelated to the bug, you can use the setting `fsharp_single_argument_web_mode=true` to align the closing `]` to the start column of the expression ([see video](https://www.youtube.com/watch?v=n4C3f2b32O8)).

**Comment by halcwb** [comment] 2020-08-14 12:47
@nojaf Thanks! using that setting it's much better. I indeed use Feliz. Could there also be a setting that makes sure that all indentation is using the tabs columns. Then you'll never have the problem that with changing the indentation you run into compile errors.

For example:
```fsharp
let cannotIndentList =
    [ "item 1"
      "item 2" ]

let canIndentList =
    [   "item 1"
        "item 2" ]
```

**Comment by nojaf** [comment] 2020-08-14 13:13
I don't think I understand what you mean here 😅.
Please create a [new issue](https://github.com/fsprojects/fantomas/issues/new/choose) using the `feature request` template.
We can further discuss it over there.
I'll keep this issue to solve the original problem I mentioned.

**Closed** 2020-08-18 19:39 UTC

**Comment by halcwb** [comment] 2020-12-19 11:28
@nojaf I ran into this issue and created a post about it to explain my view: https://informedica.nl/?p=203
