### ISSUE TITLE
Line of code including a backward composition operator causes error

### ISSUE THREAD

**Issue by thomasorton-i2o** [fsprojects/fantomas#1998] opened 2021-12-21 16:04 UTC
The following line within a block of code causes Fantomas to throw an error:

`(SomeModule.doSomething << SomeModule.doSomethingElse) (fun x -> x)`

The error starts with "System.Exception: cannot determine if synExpr Paren". I have reproduced it in the [in the Fantomas online tool](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAKAyrAtogsggK4A2iAdPLNngC4AWAlgHYDmYAPB2DQcWZWq5EDFqwCiJAM6IAlGHQAzIszAAPMAFoAfOtmQANOCgzatMVNRgA2sYigIjqABJaATwAOyNJBa1Ddo6QzgBuAIYkRN42gU4ADEZOTpAAksxIzLSYjABeyIlJEAAssWAAuoEAvgX2pcHuXla%2BmQGFweGR0baFEACMNUmQ%2BGFqADIsiKOIbAytPb0ATHGlFU7VgQ6Drp7RkABGsLAkc8mhEVFW3T0LA8mYiDiMcCSwzACCtOLpAPKK48z5UoQRQRGQrKoDTanBq7A5HE5BM6dS5AsAAZluQUwHjC0EQACFEIpYAAnRAABTCJLCdEQJIRTloJKi4LWkLq20aPjhx0x7XOXVRRUxEEg2NxBKJpMmsAA7nToGEZGkQrBFeZXgzHEyWYVVo51k4oYiYU0eVr%2Bci0FdCgBWEVQcV4wnEskAVQ8XhJiuVzFV6sYmodIOkiFZBvZbU5sMOvI5HQu1tRADYHWKcc6pWSAMIkJVSbOvKQ66C0Ula4GgsN6iEbDmm7mxi1IxMxHpgADsaadktdBAeezpFbAIbBNbZdajDag5r5LcF7YAHN2M73pYWXsxh6Pq0l9RBDY5jaLo2am3OEwuegBOFcSt6KWh0ws4HBhYc63dOfdgQ%2B1Kc7Ge8IXgKKLtr0CSoumEoutK9yPM8Qaoju4YHpGWzTvs57xqBSbgf0UE9g%2BT4kvBTxHEh7afqhv7odCgGNsBOFWm28w3FBaQZLQ3zMAAKiSbgAOqMLMwZVjRf5gMeLiYbOzGtjaSS9BihGrm8JKwCo8AACKICQjCPCRH7Ml%2Bjg-pJ0n1AxUB%2BM2l5gfMwpQcMagpIovH0NMkgyJg9CkrQwnwKJQrLOOEaThh1nNP4IEsYpTi9PazkjGkiiMGo3xemEZYkuIageGSUhSIGW4OraoV7rWRr1lFtmxQpqK9KmyVqAASogcAkvAgXBe2RQVd%2BVVHjVXI2S09VXoUvRdi17WdfAAByRA4IOJK-CkT44JYDq9BJdEmlFOCkOY%2BkAgAYqSb5mHSvGARNDlTcuUFzaS8D4MdjCnYgF0kldRlptA9BUriJEAPqyowQX0JAe0RfRo3RXZuGsVNt4tep1JuN8JLjMWPXQw6-Ww9VAEI3V8mTUkSxpi5GNhFjOOMMWS0rXS62bdtjXE8NpO7EdJAnRMP1-Tdd0Uw9VMEe2kB0wzuO0O9AufULl3Zf9UGA8DpZ0uDkOzNz-6RWT43i3h1zsdLLkAGoCviLDwGI%2BPDouA1mUNhvw7s5NRvZZuFAsKmWyMZ0qKWJV2%2Bkjt6wTIUG1JI1eybPvI-FjgLE5QdqNpsC0AA4iIeUFYgRUlU7ZWuxA5n7SesnYcncWogsSWWx9X34i80AANb4tSXciFIPGYDSiAbstpXIeJYVoXDB0I3J9cNe2CzNdLC2ILKbciPK0y3V4ulpcwIklW86T4AOdKc%2B2KFT7RM811F89bL7KNUzN0sANKIIgHhuR50xpEPPA-xARX0npVCcJMjaJxiqbF%2BTgFhPUzpIR4Uh6Bl1jjfCyCcgJxgXpTeBaNpbZDYGQdSrBlrTACogPYhAkDbjAYNCBPMoE4KRg3dsaJILSzePpVgzAQ7MDDq8bIfDspEDJLxWAnFKHZRKvQ0McdLKnkYrgp%2BKdURoilj0GWAs6TMFkSEGUbAz6sxJPvFgR8izyLHOA8KkDPasPun7JIaILbaMVuYYBowaR7HgGEXMsBipsDXhvCY1jTKV3dvHXmjjYGpwgGiQO2jtJMzCHsMgyCmb0EwG4TIIxwmKOwT4aY8BfjAMwO4MgbDF49DRBnbRXxSl-DCWmEgigYaYOrjJB%2Bdc1HsNqc3bRn9v7SMyGkHuYRBEx1AQozpd9ulz16acZ%2B8T0Qr20e3SZndgFSHUppdIa9iyIDeq3CYhdCrFSsQ6aicz7GzxjExPBEsnBojfhsqksEyQpKkNAEkBkWDZWOW6Q%2BrxdLQDzNSDU48Zk2MYXY5hDiVHVPwY4NEiDtEVL%2BaWWhICejX1sQeYwZQCi%2BCkGdYqVgUKVCAA).

(I tried to use the "Create an issue" button but I got a GitHub "Your request URL is too long. " error.)

**Comment by nojaf** [comment] 2021-12-21 16:24
Hello, thank you for reporting this issue.

I believe the problem is occurring around:
https://github.com/fsprojects/fantomas/blob/2c6c967d20106f5f2e11c6a47ed925f567f1b207/src/Fantomas/CodePrinter.fs#L2031-L2039

We try to see if the `(fun x -> x)` is uppercase or lowercase. I think in this case, we should just add a space between both the function expression and the argument expression have parenthesis.

A potential fix might be something like:
```fsharp
            let sepSpaceAfterFunctionName ctx =
                match e with
                | Paren _ -> sepSpace ctx
                | _ ->
                    match List.tryHead es with
                    | Some (SimpleExpr _) -> sepSpace ctx
                    | _ ->
                        match e with
                        | UppercaseSynExpr -> onlyIf ctx.Config.SpaceBeforeUppercaseInvocation sepSpace ctx
                        | LowercaseSynExpr -> onlyIf ctx.Config.SpaceBeforeLowercaseInvocation sepSpace ctx
```

Are you interested in submitting a PR for this?

**Comment by thomasorton-i2o** [comment] 2021-12-23 09:49
Hello,

No problem. I would be happy to submit a PR, I'm just a bit busy at the moment. I will try to submit one tomorrow if that is OK.

**Comment by nojaf** [comment] 2021-12-23 10:16
Sure thing, take your time. Thanks!
Please review our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#your-first-contribution) and don't hesitate to ask any questions you might have.
Good luck!

**Comment by nojaf** [comment] 2022-01-25 08:37
I believe this issue was resolved by https://github.com/fsprojects/fantomas/pull/2036.
To close this issue, we can add a regression test to be sure.

**Comment by knocte** [comment] 2022-02-03 07:15
This can be closed now after the merge of https://github.com/fsprojects/fantomas/pull/2060 FYI

**Closed** 2022-02-03 07:31 UTC
Labels: bug (soundness), low-hanging-fruit
