### ISSUE TITLE
Wrong anon module formatting when filename starts with a digit

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#408] opened 2019-02-01 08:20 UTC
Consider file `60Seconds.fsx` with following content:

```fsharp
let simplePatternMatch =
    let x = "a"
    match x with
    | "a" -> printfn "x is a"
    | "b" -> printfn "x is b"
    | _ -> printfn "x is %s" x
```

It's being formatted to
```fsharp


     |
     |
     |
module ``60Seconds``
let simplePatternMatch =
    let x = "a"
    match x with
    | "a" -> printfn "x is a"
    | "b" -> printfn "x is b"
    | _ -> printfn "x is %s" x
```

**Comment by nojaf** [comment] 2019-02-01 08:43
Ok, I'm able to reproduce this in Rider. I think there are two problems:
- A module statement is added where none existed.
- Preserve end of line adds pipes and messes up the code.

For the first problem I'd like to know how Fantomas is called when pressing `Reformated Code`.
@auduchinok could you point me to the code in https://github.com/JetBrains/fsharp-support?

As for the second problem, `--preserve-eol` will go away in the next major so I'm not that eager to solve that problem.

**Comment by nojaf** [comment] 2019-02-01 09:59
Well as might know by now I'm not sure we should preserve user formatting.
- Other formatters (based on AST) don't have this. F.ex [prettier](https://prettier.io/playground/).
- Fantomas didn't have this option for most of its existence. I feel like we merged it in without fully understanding all the consequences. And the current implementation has a lot of issues, even more than [logged](https://github.com/fsprojects/fantomas/issues?q=is%3Aissue+is%3Aopen+label%3Aarea-preserve-eol). And the original writer of `--preserveEOL` has [moved on](https://github.com/s-trooper/FSharpFormat).
- `preserve user formatting` is also a very broad spectrum. Where do we draw the line?

Feel free to further discuss in #390.

**Comment by auduchinok** [comment] 2019-02-01 10:02
> Other formatters (based on AST) don't have this. F.ex prettier.
R# and IntelliJ do it for other languages. I believe as a user I'd expect it to do it for F# code as well. :)

Thanks, I'll try to add some meaningful input there.

**Comment by nojaf** [comment] 2019-02-01 13:50
Is there any way of knowing the value of [parsedInput ](https://github.com/JetBrains/fsharp-support/blob/191/ReSharper.FSharp/src/FSharp.Psi.Features/src/Formatter/ReformatCode.fs#L34)?
What would the exact AST be? Could you show me how the AST was created?

**Comment by auduchinok** [comment] 2019-02-01 14:02
It's coming from [FSharpChecker.ParseFile](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/service/service.fsi#L408), called inside [FSharpCheckerService.fs](https://github.com/JetBrains/fsharp-support/blob/1b837d6e75cb6c6b916d4efd4c58a3c689fed508/ReSharper.FSharp/src/FSharp.Common/src/Checker/FSharpCheckerService.fs#L56). It should be the same result as when using FSharp.Compiler.Sevice.dll from NuGet inside a script, at least before the recently (yesterday?) released FCS, due to changes in https://github.com/Microsoft/visualfsharp/pull/6027 which help with dealing with anon modules.
Otherwise, If you want to debug our code in Rider, you can build the F# plugin and attach to R# process calling everything discussed above.

**Comment by nojaf** [comment] 2019-02-01 14:44
Yeah I knew it would have to come from `FSharpChecker` but was more wondering what `FSharpParsingOptions` are passed.

**Comment by auduchinok** [comment] 2019-02-01 14:47
It's default options with file name set and `IsExe = true` for scripts (i.e. this case).

```fsharp
let getParsingOptionsForSingleFile (file: IPsiSourceFile) =
        { FSharpParsingOptions.Default with SourceFiles = [| file.GetLocation().FullPath |] }
```

```fsharp
member x.GetParsingOptions(file) =
    if isScriptLike file then { getParsingOptionsForSingleFile file with IsExe = true } else

    getOrCreateFSharpProject file
    |> Option.map (fun fsProject -> fsProject.ParsingOptions)
    |> Option.defaultWith (fun _ -> getParsingOptionsForSingleFile file)
```

**Comment by nojaf** [comment] 2019-02-01 14:56
Ok, thanks for all the pointers. I can try and write a unit test now.

**Comment by nojaf** [comment] 2019-07-12 12:49
I can't reproduce this anymore in Rider.
And I've added a regression test.
Should be ok, please re-open if needed.

**Closed by nojaf** 2019-07-12 12:49 UTC
Labels: area-preserve-eol
