### ISSUE TITLE
Fantomas hangs indefinitely when run

### ISSUE THREAD

**Issue by willd-i2o** [fsprojects/fantomas#459] opened 2019-08-12 09:56 UTC
### Description

After installing `fantomas-tool`, when running `fantomas` against a file or folder, the process hangs indefinitely, with no output being produced, the process needs to be given a force quit `ctrl-c` to return back to the terminal.

### Repro code

I have tried with both the stable channel and the preview release of `fantomas-tool`. I cloned the repo to try some further debugging. Running `build.sh` was successful, with all tests passing. After building, if I then run the built `fantomas-tool.dll` directly against a file, `fantomas` seems to operate correctly, and produces a formatted F# source file.

Windows 10
.NET Frameworks 4.6.1 (and later) SDKs and targeting packs are installed.
.NET Core 2.1 and 2.2 are installed.

**Comment by nojaf** [comment] 2019-08-12 10:22
Did you built from the master branch or the trivia?

**Comment by willd-i2o** [comment] 2019-08-12 10:24
> 
> 
> Did you built from the master branch or the trivia?

master

**Comment by nojaf** [comment] 2019-08-12 10:26
Could you try the trivia branch? If you there encounter a problem that you can share with us, we can act upon it. Otherwise I don't really see the call to action here.

**Comment by willd-i2o** [comment] 2019-08-12 10:31
While experimenting with this, I tried running `fantomas` from different terminals, I had been running it through `git bash` before, it seems to work fine via  `cmd` and `powershell`, so I guess it's not playing happy with `git bash` for some reason...

**Comment by jindraivanek** [comment] 2019-08-12 11:24
Interesting.

Can reproduce (in `trivia` branch) in `git bash` and `cygwin`. However in `WLS bash` it works fine. Looks like some problem with `mingw`/`cygwin`.

Don't know if it is even possible to debug this, and if it is that important issue.

**Comment by willd-i2o** [comment] 2019-08-13 13:13
Yeah I wouldn't know where to start with debugging this, and whether the problem is within the scope of this repo at all, but I thought it would be useful to document what I had discovered, in case anyone else encounters this and starts googling, because I couldn't find any mention of it elsewhere.

**Comment by nojaf** [comment] 2019-08-30 07:38
I'm going to close this as it doesn't sound actionable to me.

**Closed by nojaf** 2019-08-30 07:38 UTC
