### ISSUE TITLE
Fantomas reports an error when formatting interpolated string with tripple quotes

### ISSUE THREAD

**Issue by object** [fsprojects/fantomas#3049] opened 2024-02-22 10:02 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAbRAXMBXAzogE5gC8YAOpAIYBG0VFAds5jgFb6xNlgAkfRpEZNgzCFQCW8KmioBBAEIBhKgBpxlSE2oBbRLK3BgBYgF8z65mYDczIVUhrwUQliySmAc3yowAbRcIUAhQqD4sAE8AB2Q0SE8sJyDQyD4AN2p0XDiAlLCABmcwsMgASSYkJiwAZUkAL2RikogAFnywAF0Us2bgjrSo2L8E6uSWtMzs3MCWiABGPpLIAFlqAA8AGU9ETcRvLAALcbn5gCYCju6w3pSQ5YiY3Mh9%2BAB5ADNtpkQaqMwTqUMlkcn5ZnMzktSgBRSqfb5NDoQSDoD6QK49Jb3IFDZ60WCwdCA1LA6ZgpFgADMUNSFUIRCwADFPFkAHKIADu6B2xLCWCIOQxNyxA0ew3i%2BMJvPCU1BaHBLVaNORNWi1GgiEUiA%2BsCIiAACtQiHpsMRpRB%2BYKWtdQrcwtiSbiRpKiTTJiCZhSAKzKqCq9Wa7W63awDnEaDUQgVdKwCMebjmsCWxBC20iiZivEE12i2WeuZgABsvsg-o1Wp1eoAqtFYkQI1GmDG45IE76PllCKmIHbQg7kZnndnpe6yfKKQB2EtlwOVxDKdCR-DKbj4S3QLC6xMd9Bd62Yu6ip0S4du0lyvIFgAc07V5aDepWiF0tDN7c7Kf3wsPGePUBdI7nvmcwAJy3gGFbBiu6BthSO57iUNo9umDx-pAAFnnm5IFvMRQUqWd6IPIHxYMQK66Lo1CJsm3ZgL2-S-k8Q5SphHrYaciz4TOkF6jUz6SHAMFMNuH60fRYD9uEaEYbmbHjjhkJcYRxGkUQfG6AJhKwQWNFfmmP6oUxJ4sbJY6Xqc1JKQG8hELAuCVAAIog3Iaap1ECp%2BiEHvaR5GVAiSAVh8mnEq%2BFrOsZQfAAKoc%2Bw1IcupYAA6tIRyJpcenIQZOJ%2BaMSSsWZColPMPphRskUxfs0K7r8CUMil8Bpb6hYZV534%2BYx4r%2BWMBUXkVYTzMWZURUwHySOsbx1tQm5ENC6zRHq%2BD4K2wm%2BlerVhEhdEoTlXV5YFcnmS08xTsNABKiBwEQ8ANU1FKtBtoRbeJkmDLlAW9cBx03udl26vArK4C%2BxCfGUpG6L4vrzGJO2Orlui4OgHjcj8jK6pR7jEFFTGfexx1gfhF1XfAKyI8jOxo0QGNuSW0CHEa6qqQA%2BhyqXHDD2Vw3tH2mX1FIXCW4U2cakRvEQ2xrrdxxrY9EDPbDA5oTzGZBUdJRnJxBarBswvUKL4uSGugPA0QoPg5DFLQ5l22c4r8Nk5IKOIJT1NYzjvNferila7r%2BsS1gpNI47FPo9NNP4XTDMbsQLNs%2Bi1svb53M9R7ePq5ZWvhQAah6iiePAnheFLibrRzHWGcn%2BWp8FLRnKFmcbIy9kbiteeVIXxe%2Bg9Zd9knzzKw8qv9aEZylQ36wObAWAAOLYHNC2IEtK2dxSpcJwrUm5TJKuHcPEBnENWvslyOxalgYb7NjsROWNTCSPGTDyJUT4mxbOkeT3DEV1mJk74V-OnR9tyLwTAm5MBbtwOoIDpq4D1FFWAFQqhYGmitESNVP4ST7sxHMf8%2BYFjOD9IBqkdAeHSCGbwL9XxEBvp4e%2BK035zHgp5Ta3le6dR-jgweu9%2BYE0zg7BEmw9C0HgNQBcsBlreGPk7NBCEWHtTYd-bBB1-4FkpHhLW89iCSH0NULIABpRAiBoiIP2FgCoihjTgOlnBUS69babz2tvLhKi5iUk1nMSAihFxMAANYInwDZOylR2RrkQCTB2Tt56LWWqudyVo2r6XLrtDhyi8GuO9h4xQRoeKIAcobaARBtEslIvAKsd9uBOWgIuY0D8ZHMKeqwr%2BySRgIyDk7Cx6ofHYD%2BJEAEuMa4lEpBnDxgdyY-A6dALptR-iIi1gUvQsR4DxwSVlJJXN%2B4p1wZ7MIlJ64eIMUY8KxsqGfC8dQXx-jEy4Vll0RpmD2FKP6WrHZY8PFSNPg%2BRAozg4-HItEXAyCH5RMXjE1aFJdIrJtmsu2jjTzV2eaESkh8PGaMKTo5B6BqoaXwNYgsTCxIuE6M0BI%2BBGTLT8PiswQA)

#### Code

```fsharp
let user = "abc"

let json = $$"""
{
  "id": "ABC",
  "name": "{{user}}",
};
"""
```
            

#### Result

```fsharp
let user = "abc"

let json =
    $$"""
{
  "id": "ABC",
  "name": "{{user}",
};
"""

```
            
#### Problem description

We configured out build to fail on fantomas errors. And if fails on this code. Here's the output from Fantomas: 
                                                                
  Formatted │ 0 │ Ignored │ 60 │ Unchanged │ 252 │ Errored │ 1  
                                                                
Failed to format file: ./src/Bootstrapper/PhobosBootstrapper.fs : Formatting ./src/Bootstrapper/PhobosBootstrapper.fs leads to invalid F# code

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 2024-02-15T12:00:55Z - 0700fd6ec8555a4d65e11295a4a79a0fc9131f4e

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by dawedawe** [comment] 2024-02-22 10:30
I'll close this as a duplicate of https://github.com/fsprojects/fantomas/issues/3012
It's a bug in the lexer of the compiler...

**Closed by dawedawe** 2024-02-22 10:30 UTC

**Comment by nojaf** [comment] 2024-02-22 12:34
Hi Vagif! Thanks for the report, at some point I took a look at the lexer but didn't immediately find anything. This is a more challenging problem for sure.

**Comment by nojaf** [comment] 2024-03-01 16:10
Hi @object, there should be a fix for this available in https://www.nuget.org/packages/fantomas/6.3.0-alpha-008

**Comment by object** [comment] 2024-03-04 09:05
Cool, thanks a lot!

**Comment by object** [comment] 2024-03-04 11:35
@nojaf Out of curiosity, what has been changed in the fix? I checked the commit files, and they only refer to package changes

https://github.com/fsprojects/fantomas/pull/3052/files

**Comment by nojaf** [comment] 2024-03-04 12:09
The problem was fixed over the compiler side in (https://github.com/dotnet/fsharp/pull/16774, https://github.com/dotnet/fsharp/pull/16785 and https://github.com/dotnet/fsharp/pull/16796).

https://github.com/fsprojects/fantomas/pull/3052 mostly updated our source dependency to include these fixes.
