### ISSUE TITLE
Shortening an 'if' condition causes compilation warnings about indentation

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#1374] opened 2021-01-19 17:16 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAqgC4AesAwrAJYB2AgtHFjUWALwA6NEEertRRACcaAQxxgAyohrwACqICe6GUS48NYABSjGsZkTQA5WEPTjiZBkxYBKdZohbSAWURFR8UR7QAVIaI0AM66RFSwNG4eXh723I7aSEFhYmERaMlCtADmcQnaopgGfgHBAGbCdEV2Do5aAA6iQUEA7qbwGURZNLm1mpzxjlRl2gBGTYjW%2BiwAdHJYozhU0HTw8EKIzTMAogCOWOJBiZsp3uE0ADRSXTmU6I1ZQREzAJI0AG6iWYFE5LhEWA2L2yNFMiHIE1stjARAAFjI%2BvkAlQgvgACInWhnCJ7A44XywADyWWytEgF3AUFRRBS2SCqDAAG1KRBQI5IAASIiKerINCQATklk8TmfHBYPlM4UaAAMFPykDeSBYkioAC9kPKEgAWaVgAC6woAvlrWXrOdzeQyBSwheyOWKJQzmfkAIymzSQFyiEgAGVoiF9MmycLtCQAHDK9YaNCbhWzPVyeZLIKNYLAcGGNKLxE60C6EgAmD3Z6ToZYZiJ0IjbWSEsr%2BmiavUQMqHRDR40ehPZpNW-lpjNZkUO3OSguOADMJZFkka0EQACFEGUwQoAipBEJhxouhLO7Hu%2Ba%2BynB5mZznxeOW2BtTOIJA57olyuwb7YC1hNAJm93rBv2kNA7jwe4do4MY8HGGg9iOlqnum57Ho6175AArPeUBPguy6rhsBD1LyQjfqiv7-tiQEYW2OCogekFHvacHWmewGXnmUr5AAbBhj7zi%2BuHgjgTRBJQwR7tARCmMBrbtrREBQTwMEPieTEISxo5Xs6N4AOzcVhfFgm46CjMIUlgFRNHgV28bHoxA6qRe6lsROmjhrpvE4WClA4BEpnmWBmgQXJ9GJrZUDMQ5yGafkACcbnPnQZRbnc5imaBslgPJZoMcmKlDhFY5RQkrpyjePHPh5GxlhW3kUTefnpZlYCKVAyl2XlSEFfmN6uu6pV6QlW5VXANWpUI%2B6WYe1nZf2YX2R1GldW6xalUqqiEjQ-iKAA6lQoaUTJE10VNIU5W1iH2pFi1FdOfW8XQQjTPAGJLOWW6jeNAVWdBNmnVAgr5Qt7FFXepXeiQLxlL48I0Ns1GIJIsKmEQO3wHtN7alGh1BcdvahTaRBqZdQOOK66Ggz6bxlFQJCEoR3imNsJD1BszTnKZqGY59k3fdNKb-fNTndVx5MkAASogcBCPAKNo-kGMNcFuO-fjhOdcTmiujpIvi5L8BGFgRnCPWLyCOg9IYa6Cs47ByvoP8VBLE2ABipjmDSwi%2BDlAOC26rmlTr7QuPbjuIC7ZjeG93HQLCXyhMIAD6LRUKjsKQFbPMnTNKveyhRWxSL90BIoxL%2BskMupxh8tYxlis21n-MXWrzkaIWJUKmDhdKCXKJEPrhtCMbpvm916cKT9Wd2zgYQh2Hbtbp7Vo54VjiFr1Cqd8XQil0QQdTw7AazxHJlRzHATiQnScp2n1eNc1FrKw3iZE83PCFst7c%2BgAamOi60PAOTl1MlXLmR0M5K3rraJeV0V43Q-iQJ2zBxLnF-rIABydZY6k5hoQKNdrZKTxo-Xsz8byFhBnAtEsAiAAHF3CM2ZpsII5xAEYQ5qPLKmd4LtUboDF%2BEBCxk3bsHAMi5vLQAANaLjPmI9wQR1qSEKOCDMBtar5HqjfWu%2BDlbhQFrnFewsFRGEQC0EOy4iCfhkAvRAGIqY0F2ucOgshDLGSEMPVRB0QHYzAXXTh50n5NxIVrBUABpRAiB6gQyhjIN48iVCNmbG4uGbCmrjz5pAnRy9NCFj9nA2G5YgiwmYejLBPAcG3xSblXxRD-H5ELPnBUqoeh4HutkA2qgtqIFGC4BA8SEhqI8bgrxmis7aO4T7BIk424JEgHQJYIIEE0CQREVUIJvCAkQASVaLByK%2BXcdgr6Y9eYVNVjwm8k415TJmVuVIVB3iBgiNkJxwhrG0DsREVxvTdklP2ew8BPjjljKnO-KZu8whxN9IUUYXhyDeUYT0QxxiAw7MSeovBLU8YjL8Sc-Ik5YFTLRCiUQixEC5JRLCSQigtkkCRRZfpZTDn8hkPAescTJDcjwP83RmhJxkKmbWJlDZEVRyEDgMo19aUaLRVouaozOUaEnAIqZrKsjiS6Ugal-k9mxkpPqLUAoghO0YQyeqRogA)

#### Code

```fsharp
module UtxoCoinAccount =
    let internal SendPayment
        (account: NormalUtxoAccount)
        (txMetadata: TransactionMetadata)
        (destination: string)
        (amount: TransferAmount)
        (password: string)
        =
        if (baseAccount.PublicAddress.Equals (destination, StringComparison.InvariantCultureIgnoreCase)) then
            raise DestinationEqualToOrigin
```
            

#### Result

```fsharp
module UtxoCoinAccount =
    let internal SendPayment
        (account: NormalUtxoAccount)
        (txMetadata: TransactionMetadata)
        (destination: string)
        (amount: TransferAmount)
        (password: string)
        =
        if (baseAccount.PublicAddress.Equals(
            destination,
            StringComparison.InvariantCultureIgnoreCase
        )) then
            raise DestinationEqualToOrigin

```
            
#### Problem description

The above result causes FS0058 warnings:  Possible incorrect indentation: this token is offside of context started at position (638:13). Try indenting this token further or using standard formatting conventions.

#### Extra information

- [ ] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [maybe] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 01/17/2021 13:01:42 - b36e5a54dd3a44922d12f7bea8a7fcca2035764d

```fsharp
    { config with
                MaxLineLength = 80 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment] 2021-01-20 07:36
Hello Andres, thanks for reporting this issue. Although it is a duplicate of https://github.com/fsprojects/fantomas/issues/1349, I prefer to include this as well in a unit test as it has a much more real-world feel to it.

I believe this can be fixed by adding another match case in 
https://github.com/fsprojects/fantomas/blob/b36e5a54dd3a44922d12f7bea8a7fcca2035764d/src/Fantomas/CodePrinter.fs#L2293

Adding
```fsharp
| Paren (_, (AppTuple _ as ate), _) when (isConditionMultiline) ->
                            sepOpenT
                            +> atCurrentColumnIndent (genExpr astContext ate)
                            +> sepCloseT
```

will capture the function application and put it fixed on the column after the opening parenthesis.
Leading to
```fsharp
        if (baseAccount.PublicAddress.Equals(
                destination,
                StringComparison.InvariantCultureIgnoreCase
            )) then
            raise DestinationEqualToOrigin
```

Would you be interested in submitting a PR?

**Comment by knocte** [comment] 2021-01-20 09:07
> Leading to

Thanks for clarifying the expected results!

> Would you be interested in submitting a PR?

I'm too busy these days with a project and don't want to do context switching, but might assign this task to my team (Afshin, Humberto, Mike...). Thanks!

**Closed** 2021-01-22 14:51 UTC
