### ISSUE TITLE
Splitting list results in code that doesn't compile

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#2201] opened 2022-04-15 07:25 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwA5AZQB10bsEBXAG1IDFZYwBeGiCFgC5gAQpgBOACgCU3Xn3kBtAD4BGJQF0aAgJ4FSACVgEACpm1NYmeABUAMgDVZ6eUrAB5BgIDmsAJbovAGFba0dYADMwfwE5CFcKAAtYMQFAhMx0dEQmAEl4MAio9BjnPlxsACNEMTAAfVqAOmtYAHFELLFfaDt7aSd5eUE67jAAQTExMwa4dGhMAQUwdlgG0UkpAG4ljlXxPs1SgbBpGkgAGnAoPEQBAX8vPFQwBUuIUCPIABIdPSfIaPOrz4XwAbpgmAxkGgXkcIAAGC6wqA5dBIYoUXwAL2QiNhABYgRB1ECAL64t6EqDfXRQqAA8nAz5giG0mGwlQM%2BSQACymAAHrZ-IhbO0vAIEoCkSoAExwynE%2BRkoHvAZfH60yDteBucKCrIUHQsSWqpngyFPNlHaWc4EAUVROr1OMpEEgTHCkHlpIZKq51N%2BaEgFQ4TGNfuZ5uhLrAAGYba6UdcUqx-OCyIgAO5MIVhgYCMSQr2Kn2UtU0v7B2Chm2gs2s6N4%2BNQCiIbBdKuwdCjAT27W6nNN8Lg65FvhK%2BS%2Bxnqish3Ou00si3RgCsTcgFCIJGEiHCyUQpkmuAE1TnfHzhaOCrHJY%2B-o1lerpYXkee0YAbGuN8RENvd2JhbAGbVHM1woiCsBzHcnanhA56IKOEDjnwk7ztOgYPqetaLlGSIAOyfpuP47nuACqBB6GIIGIGBEHzL40GDsO8GXt6ypPmhUAYTWz71kiAAcBHfr%2Be6BEwmB4HggSdng57QAIyQwWAQ5MCOLHFmxt4cUGs7cRGvGwgAnIJW7Ef%2B3KtlUYiKcpqkDFeiE3iaWlcU%2BelLlKCLRuuhHCf%2BUkWOg1lMQhYBIRSmnluhOmuXW7nshyXlfiQozhMeYhSdg2CYIpcEhWFYAoVSznRbebk4ey1qJT5pmIC2bZwAFQUqcxdmsRO7GRZxJUmmVr5SnGVXfilaV1e2jVNrlanXhpTmddpVaYTxcVHCojZeSiaICG46DWGI2gAOq%2BOKTW2fI9mhY5frFQtumxeVK2roNyViLADCogAItkvhtmlOUFi1Z1tchHUBnSxSLb1loDCoH5ebyfI5OE1gJO0trNYkyQCId8DHU2eJylNDkzVdc30jF2F9ey%2BFw-yKLhL4fJuBR8zJLafIEP%2BEn0YFTbLgTrXqe1EWg-84O3RTUPyCoAk03yABKiBwGI8DY7jDb84DgvA8LGpk6Vd2UytRmywrSvwGQDCVNUOo5Me2CPE2Kh5ZdU5zdgzB3NmWTsGIWW3NU1jluLL6S3wsprqbyTwNyHu%2BF7iA%2B37v1rtA6STHJ1S1Bmvg4xKzvE67It6z1BuhxA0oJUiPL8uMkzaG4YiCjJqsSnjGt8Od%2BWFWWRdi%2BTIfRtKlVV-DtdmA3TcCBbVtiDbdsO9GTuExdBeoW7sfx4n8xpYHvzB-pVoDVXY-143vgyTHTCe0KW-%2B1ZKdp8QaVZznx350Ls29wIEOl4Pa0j-yewdZhD%2BHgPcFuik%2BLtyJEDcKn9dZ931hLQej0AF8lYG9OS3MQGonAa-Vu6t37a3gX8Yu4Zf5ImlLDNB71YACDaD2dmnM8DcwgbzaBYBO4uzXiLFySCB6UOpiPDeQphAWGgAAa2EOnCRNw8DbQoDgRA-lLY82jDZAGHdYEFRBvebq5DkGUJllXdMWZRE3CAu0XeiBPr03QEdbmoxUTmRngvJEGiiFwJJrw-RjJIaD2NlXAA0ogRABBEbI3aCiRRuAnQnU0TArWXjC4IO-vvZaAwYyeTQWjNseAEhsMIcvLuuiZw3X7gfTJldYTrnuCwcYXhLbtCxogCo3IEDOnccFYp3CipzT4SXQxsIYzDxqaMbMXh0AYNmFBdAGJJnzAYP%2BZoG1ml0QYuo7pAtpof28Xo8p-DKnyBjEfMZV9qhYDuCCACAQXGWVsf4Bx0l4meJ0TrMpj5DkZOOf-Gpl87hOlsDgCo8BMCiVgCwgIpj44vJ6avPpPiDmDIEcM1BNT3rn0wBUFguTz4JAoNoYo-JYXbKJrslJHyf5DKODGahNSQlhNWcUFE0iMipxJZrHZxC9mUvSfdTJQialiIyBIp0eBxivVROmGSiBo4iKyGzDm%2BAWHPImv9V53c7y8oqd8vgMZjFCvEL5Gx59oCdDbJc2VJF7Gdk%2BtAMSkxZkcq0Ukt5JCopIoMSimlgSaly0wAsl6EjnWJK5cknh%2BzPnIqOXwfGn58xdAEO0pAIbOGkkuOoXE-w8CsBYU8DxJIgA)

#### Code

```fsharp
namespace NS

module Foo =
    let Bar() =
        [|1|]
type HopPayloadTLV =
    | OutgoingCLTV of int
    | ShortChannelId of int
    member __.ToGenericTLV() =
        let _ = Array.concat[ Foo.Bar(); Foo.Bar() ]
        ()

```
            

#### Result

```fsharp
namespace NS

module Foo =
    let Bar () = [| 1 |]

type HopPayloadTLV =
    | OutgoingCLTV of int
    | ShortChannelId of int
    member __.ToGenericTLV() =
        let _ =
            Array.concat[Foo.Bar()
            Foo.Bar()]

        ()

```
            
#### Problem description

It doesn't compile anymore; gives: `Successive arguments should be separated by spaces or tupled, and arguments involving function or method applications should be parenthesized`.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [maybe] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-04-12T06:26:27Z - 7b35c8912c8a039bc443705019c7f15f5e6614c1

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment] 2022-04-15 11:15
Duplicate of https://github.com/fsprojects/fantomas/issues/2158
Add a space after `Array.concat` to avoid the new indexer expression.

**Comment by abelbraaksma** [comment] 2022-05-10 10:20
@nojaf,  unfortunately, adding a space can break code. Consider this:

#### Working code that fails to format for the same reasons

```fsharp
(configureCorsPolicy
    readOnlyDict[$"{hdrKey}:0", "X-MessageID"
                   $"{hdrKey}:1", "Authorization"])
    .Headers
```

#### Adding space to prevent the list items to break

This code does not compile anymore, as the compiler thinks the function `configureCorsPolicy` now has two arguments:

```fsharp
(configureCorsPolicy
    readOnlyDict [$"{hdrKey}:0", "X-MessageID"
                    $"{hdrKey}:1", "Authorization"])
    .Headers
```

This is similar to `f dict[a; b]` (`f` has one arg) and `f dict [a;b]` (`f` has two args) not being the same.

**Comment by nojaf** [comment] 2022-08-24 06:21
Fixed by https://github.com/fsprojects/fantomas/pull/2446

**Closed by nojaf** 2022-08-24 06:21 UTC
Labels: bug (soundness)
