### ISSUE TITLE
Content of #if block removed - Breaking Code on reformat

### ISSUE THREAD

**Issue by sadgit** [fsprojects/fantomas#801] opened 2020-05-01 12:35 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBiAlgMzAQgGEB5AWQAUBJAGQFEARAHQCcGA7Zt9CsByAlAPRIAbgFcAzoiYCAggAc5dAIYAXJQIBKsJQFtMrAOYDWcncYSIA%2BjoSiANonEClAL1FNEAWmyjW0FZiwrOKecB6eKrCwdk4ARvq8HKzoTDyQJJjQTLDisNgqAHQybh4FAOqIsQBSsLHiBQASOYXwdnaJLMmpvADKAJ7iKog6BQByiIUNKipyBQBisEw6qgGGBa3tkElJsHKIrGAZWTl5hcXuiOWVNXU7ewdH2bn5RSWXFdW19U2D253o%2B3gOD%2BnDs2ngaQKBQE4gAFkoPPABKIAnZMAFHAVsOIAB4dNh3fZgABq4jkSlYBQIsB0NkpAFVUejMI4QckwUoIbw6JglGCUXNfP5ApTsXitp1CQdSeTKXQaUp9PMhQEguI2Q4VGANL4ABQ6RziJQGRBoQZMfQGAA0YEQOMQ0BRIuprCGOJUaBo9sdqtYLrdKhtYIMaAAKkwlNBEGULUMmABKMAAXiSEAgmrAwYorGwsGTmdgBgK2dzqbTGZNKh6E1WBnz-UGwwKNFYwkw2VYBtdBQA4hMW22O12VMSEbzYg42Wnbd6nUF-XaVGWIAAfAB8YEFfl9PdEmAhWZzsGXYHXYEwBlYi0QU7TBvERpNp43RBRBR5fNgb4--JUW%2BFQRFNAUZyFqh65mAlbVtMlpJJAVrgFAkgwYY4ioGAADaiEQKA04QJAAAkKh9Hs6GQPoKjwdhaaEcIfKiMgaBYXhaYAAwISx%2BHZkgro9OSUajKIOhUZxYAACzURAAC61EAL4cWmuF4YRxGkWg5GuiJykEXRdgMehzGcQAjApLGQGQxrRvuKiwlpLFGQATKxklgDJ07ydRSnTipJGMVAsRRHYdk0Tp9F%2BYZLEOaZynVnocBgqwMgqC28BENgVD6Mg0XTtgfKSC5blph505eSFql%2BZAAXRMF%2BGhXp4UuRAADM2U0XxkaIAAQoguYeBZEYGnGNVpioTAMQVcnRaVtXlWRVVBa1tFhQZjXia1%2BHtVG3W9YgVCwAA7lI0BKJI2bCLAx2%2BsNECjeNLGFRAxWKS5Plqf5gXDUt9UraJACs61QJtXU9de9IKEdJ2IGdF2qCK11gLlMSIBN7lTS9RG%2BXNH2LXV%2BlMatABsAOQED23XgQdgneILrmqI-iLPDiP5fdk2eejs3qfNn24w1okAOzE6TIMeCQwyxFIjN5cjLOo2zZkY29lXY%2Bjul45hq0AByC-xwM7dSCWS0jKNFWj8sc%2B91U46rvOcQAnNrHUyPkUjUrSSjw7d0t4Q9YBPTh7OY5zyvy9bP3Gexq0kzrZMeLFmTREEhvM97rMlQHitc1by346JRkmZHQNO3GcfxYnAOe8bj2m9p5tK5bKvZ%2BrudRZH3H7CoRCsOGfRlOitkA0zXvTj7ftgNNUAKxVmcN99OfGS1Bc6zI2S%2BPAdCIGiehDeXY1D2mI-V95k9kRR3Oh3P9licTJBKDiFDYKGsL7DQSM9LCiwqL38A2fDYnOTLJs5Y10DlAU%2BWdZ5N2Mv9SON8745kwDiIgewIyRCYF6OQHgHxwwBr9f%2BKdZZpzNiAjSlFwFqwinhIyRMYG3w0A6RY8Av4-wBn-SuvtD5lWIWAme5DVpGQFjQnEy8Ix9CIEwDKgwmH91WqwgBVcgFH1rtwkOjcKHTiMlrQRVAJidX0ECQwUjf54OHqnZ6RCM7B20ufSB9l7YwPsEyVgXUwTQAANadQjG4iY4hO49F0IgfWQlWBJz3tJUx-tzFT0sUfaxai0xOWJuMfaaInHdRUIdfYoZfLr2wPoZkQQZCsHgKLHQ4smBoQHlLNho9x6vSifXFREC4kQAcvnUSJNRqZBUCQCwITqmISkgpci4g5jiEwOhQeIBZJAA)

**Please describe here fantomas problem you encountered**

Extra lines added - minor

Content of #if block removed - Breaking

#### Code

```fsharp
#if !COMPILED

#I "C:/devuser/AppData/Roaming/npm/node_modules/azure-functions-core-tools/bin"
#r "Microsoft.Azure.WebJobs.Host.dll"
#r "System.Net.Http.Formatting.dll"

open Microsoft.Azure.WebJobs
open Microsoft.Azure.WebJobs.Host

#endif

#load "../shared/utilities.fsx"

open Common.Utilities

#load "Function.fsx"

open Domain.Functions

let Run(message: string, executionContext: ExecutionContext, log: TraceWriter) =
    let logInfo = log.Info
    let getSetting = System.Environment.GetEnvironmentVariable

    executionContext
    |> FunctionGuid logInfo
    |> ignore

    message |> Function.Accept logInfo getSetting

```
            

#### Result

```fsharp
#if !COMPILED
#endif
#load "../shared/utilities.fsx"





open Common.Utilities

#load "Function.fsx"

open Domain.Functions

let Run (message: string, executionContext: ExecutionContext, log: TraceWriter) =
    let logInfo = log.Info

    let getSetting =
        System.Environment.GetEnvironmentVariable

    executionContext |> FunctionGuid logInfo |> ignore

    message
    |> Function.Accept logInfo getSetting

```
            
#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment] 2020-05-26 17:27
@jindraivanek this is a weird bug as the compiler is returning the same AST in both code paths.
So the define solver parses correctly that it should generate AST with both [] and ["COMPILED"].
However, change `COMPILED` to `COMPILEDX` and the result [is way better](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdATugdgYgEsAzMAQgGEB5AWQAUBJAGQFEARADS1y-3rHUjkUAeiQA3AK4BnRJmEBBAA6LWAQwAuq4QCVYqgLYEcAc2E5F%2BswkQB9fQgkAbRFOGqAXhMyIAtEQk40OoEsDhSPnDePuqwsI6uAEZGAjx4mPyQ1ATQmLBSsETqAHTynt5FAOqICQBSsAlSRQASecXwjo4p2PjpAgDKAJ5S6oj6RQByiMVN6uqKRQBisJj6GsEmRe2dkDw8sIqIOGBZOXkFxaVeiJXVdQ17B0cnufmFJWXXVbX1jS3Du908Id4MQAbg8I49PAMkUisIpAALVTeeDCCTBRwEYIuIpEKQADy63G6%2B0OYAAalJFKocEVyLB9PZaQBVDFYgguMH4SGqaECVgEVSQ9ELAJBEK0vGEyCQAA04CgMlmRmMUlQYAA2gqIKAIHqoAASdQDA7qyBGdRy7V6yAGsRCiTINBa-X6gAM8tdNvoOCQOHUfWp0EQ4wk%2BitXogABZrRAALrWgC%2Bnr1utdtuNprQ5v9EfTdodTs1sb1AEYU17ILRVMZEBUCPB1Ai817SwAmN0lhP65PWtP6jMmouQBKxRwtm0FxyO9UuyNtivpvqjbJxULydTMX2UIiMIzIRf6ohCmRdpOL-uTzPD0dxCcQW326dFudegDMh5tgdUwYAQogiGWRBq0wAwplke89XUTBHTPHsLxLQcsygW9x0-R9C1nEto0-B9vz-ACgMYWAAHdZGgVQZB9MRYAo4JQkgiBoNgr1uz1Xt9UvB8jSHM1UMgjDnywyMwAAVlwqB8MQf9AO8ZllHIyjEGo2iNAlRiwGPeJEDg9iEMrHjkJHMcBKnGdnWwsAADYJMgKSZKA8hHEoqR6TCZigmWDStNPVjzz7RDDJvEz0LMl9LIAdls%2BzCO8ahRgSCCJJ8nS-PggKDOvPiQsCp9zOLESAA5oqDaTYsQelIRwbyT1S102IgDjU0CrLs340K8vCkSAE4Sp-RB5EKWR6UZVQNOYur9QasAmp1FreLanKDM64TI1LD1LLs0qHO8ZdDDgKqau03TGv0-NWpQpb8xWiyRNLctNqkwaRkwPbV0OiSJpOmazoHILsrvDrMNutaF02n0-XUSgcAAFUwAZ6ybI7fPq-zOPmoz2ty4GCrWj9HtK%2BRcgCeBWEQTFDBe8aYMmvVptmsAuMNC6c0tIGhJB1so1s6hVHxegiBhhFDmYbS%2BgRZZ1HrRtmwkqNOzSvSMvOhaoAtUybtx1txM23n%2BZwIgCHxSgDlAmJMGYfFFG8KQpHUiTRIV1H0vRzLVdZjWcdfV1Sxs3W%2Be0RBIngaWkblp2prR5q3aM9X2fy739VLKL-fxInQIGShMD3YZQ9lyz5e%2BhmmaQ4c4%2BxjmtZ94rU8YKZfyMEETDzjTC8V07lb%2BlmseWr3LNLXrdacNkcGkyFoAAa1-UDJ6mKRob6MDKrDarktqovfqvd2e%2BuvuRI7WzJhIzFR--dQyMOGGhzJw2cHZddfXi-REswNU1%2BO9ufs7rfMauv7NcTnqNsD0RKQAANKIEQIoAWQtDg%2BkXvoRAe5R7I1pvGKOc0Y7BUBhXBOlk2xg1AX0aC2R1DUGsKgouCo4wpnNFIBYdt1QpRAImIAA).

I'm guessing passing "COMPILED" does weird things when we create the AST.
The AST viewer tab does get it right though, however, that creates the [AST slightly different](https://github.com/fsprojects/fantomas-tools/blob/master/src/server/ASTViewer/GetAST.fs#L146).

**Comment by jindraivanek** [comment] 2020-05-27 06:40
@nojaf 
Related part of specs (https://fsharp.org/specs/language-spec/4.1/FSharpSpec-4.1-latest.pdf#page=21&zoom=auto,-137,799) :

> The COMPILED compilation symbol is defined for input that the F# compiler has processed. The INTERACTIVE compilation symbol is defined for input that F# Interactive has processed.

I'm quite sure that when parsing to AST, F# compiler add `COMPILED` or `INTERACTIVE` (for script files) to defines. Looks like it is based on `FSharpParsingOptions.IsInteractive` not on filename. Looks like AST viewer [parse](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQA6ATl8gGJE8MAEIAkgDkAKgFEASgEEAwtPEA1Wb37bB4sF0jLMAejgA3AK70eJxQAd7AESoAXKifmsqAWxQBzE2R7HyD2WAB9H3ZLGnQTKgAvSx5YAFp4S2RmV0RWZDQ0tlS011ZWOhMAIxRDXQEeA0gAWURmHlY0VnhXADpFZNTegHVYKoApViq0XoAJTr7oGho6vkFGwwBlAE80V1gfXslYPtnXV3te4lYeHzdc5H9epZXuNd1We1hkMFb2zu6fQGKVgIzGk2mHy%2BPz%2BHS6PX6g1BowmUxm8z2unq32gwixawENG80CavV6JjQAAsqKloCZLLkaIhcuhevA0AAPVY6Nafb5gdRoexUZC9ZSsHzRUUAVUZzMQ6Hx-EJxKaTkQtFYDOIWRyeVF7K5kEgIAAvkA) file as interactive, Fantomas don't.

To fix this, I propose to change this special defines (`COMPILED`, `INTERACTIVE`) to something different (that is not used in source code), and then change it back when outputting formatted code.

**Comment by nojaf** [comment] 2020-05-27 07:10
Good thinking, thanks for checking that out.
I'll see if I can come up with something.

**Comment by WalternativE** [comment] 2020-10-08 13:17
Maybe already covered with this issue but just for completeness sake:

When I load multiple files with one `#load` statement like
```fsharp
#load "file1.fsx" "file2.fsx"

....
```
reformatting will translate this to
```fsharp
#load "file1.fsx"
#load "file2.fsx"

...
```
Afaik this doesn't translate to the exact same behavior in FSI :/

**Comment by nojaf** [comment] 2020-10-10 13:15
@WalternativE not sure that case is related here. Could you reproduce this using our [online-tool](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBiANrAhvMAOpAGYCWmiAjAHTEDOAHkYSeYgEy2NGQA04UOogAuw0gDsA5nVRgA2gIigIKqABJhATwAOyNJAnC%2BilZDUA3HJgCue%2BSdUAGfqtWQAkuKTjhAZVIAXsgurhAALA5gALomAL4hSpFmWrqyBj7GoWaWNnYKoRCUCa6QALI4DAAyEoiViFLCABaZBZTsjpExqvEmyiUaOnaQAEawsJgtbhZWtrL5BezFbr6IALakcNjiAILCAKJeAPLE1eLBkRDEVkKdccV9UylDo%2BOTptO5cxdgAMxLpr5tDhoIgAEKIYiwABOiAACjgoThViJEFC3qphFDbLduvckgNUvoXhN-tkZnlvmF-hBIIDgWCIdDarAAO6o6A4ISecywDliWDidEqTHY0JdFQ9VQPd5PNLEoVkz5oeahACs1KgdJB4MhMIAqtpdFCOVzxDy%2BaQBULLtdEDiJXisgTnmMSficrNld8AGwa2lA7WMmEAYUwnLowYFdBF0GE0OtYCumBuYruvXxsqJroVH099gKYAA7H6tQzdYhSmthqiE0mU65xRBJSppTTnXLs6TcxSCwAOEsBstMyNbWu2%2B1Nx39TNQeVdj09goATgH9O2xGEqMjq1WOATIrtqdx6adM5Gnfd5K%2BBcozm%2B-vpOqZK3WmytGrrh4baalGcGHdeecry9G8invUt103KEXw2cZ32%2BA8JzAZtElPf8s0Ay8lXzVpFnvTxvGEQ5xAAFShTQAHVSCaMdky-VRG2QqdHnQ2cLydBdr1aP5wMHbYoVgawvAAEUQTBSHWKD9yxeiVEYlCwFbdQz0MHNOJA1oqXvcoGHcYgSMaeo9jo3xGmhYQqPgGiNTCDojwdE9p1Y9IjCA7CVVcSh1W0ipPDIBhDiNHA4yhPYGG0GE6DoS1BQ1VU7O-Y9fzQwkoFUty8w81RKF9HyGAAJUQOAoXgSzrMpBKGJ-Fs-1Sly1OAnDQkoYs8sK4r4AAOWsVZqyhY53E3VYZA1SgkIUpTkmc1ZrEwMRxLOAAxaFd1EVESP-DLF2a-t73a6F4FKWb5pqZaoVWqS-WgRoEWBKCAH0WVIKzmnG5iZWc9KsMy75KBXPL%2BMRTRDihapozK5obMquTqtQpy6q%2BjjGqylR2j9HTAZwYHQdIaNut61EBqGkbfrexyWLqma5vIU6VuCqCNtSLauNCdgwILSBMexsHhCO6mFsQM6LprK6bsRWNUUe56aLJ5L4aGRH%2BnUprXHYPCOZ0gA1clQQkeAJEkCGE1s2WapShWMmZjTWZ4jWKkWoTYxi3WvANo2odNuGKYt1zvu21WtLthhhNgYQAHERDCiLECimL3e%2BeLPcU2qXUwpH3O%2BdhvI146abOUFsGgABrUFxaLkQ6GI3wkUQEceti75PyTyb2wwt105%2Bgt2FyjnOsQFkBfBYQ2XqRnEFEshxGomLti8SsCahEmCyb%2BzJ3Jj66rnP2WdV1qOYAaUQRBtD0gz6k8avkVOc5l-HVemPXtsVMt7frdV3ag%2BM9Y6EaeOCxN%2B%2BE0U4AXbkrZGmd-oc38FICg-FJA9XqBZRAwxSgIBvgUFeiUHJy29iAhqGcCw-DvBzbY4lJDiAduIJ2Ap-DkOCtYGEJFYAEUQcFGKtF6xVSSmbeWeCrYq1UD8dmBROZzVROINh5hmRSHnn1CeEhp5Rg4bJCA8l3pP2clvDu-tBHqxEb4TEGxeZoOUeNAQUQQgGDoItaKsgm6xCAA)? That might be a separate issue.

**Comment by WalternativE** [comment] 2020-10-12 11:50
@nojaf apparently I can't reproduce it anyway. I swear to god, that it happened to me but apparently it mus have been the ghosts in the machine again 🙈

**Comment by nojaf** [comment] 2020-10-16 07:23
@WalternativE nah, this could very much have been a thing at your PC at one time.
There are a couple of versions out there in the wild. It is totally possible to find a bug locally and see that the online tool (linked to the latest and possibly unreleased code) works out just fine.

**Comment by WalternativE** [comment] 2020-10-17 13:04
Could very well be the case. I use Fantomas mainly from the Ionide integration (just as an aside: the progress y'all have made just in the last year is super awesome ❤). There have been updates since I've seen the odd behavior.

**Comment by nojaf** [comment] 2022-07-08 15:38
This is no longer a problem because we don't have the same directive restrictions in Fantomas.FCS than we had with the regular FCS.
A regression test can close this issue.

**Closed** 2022-07-11 13:02 UTC
Labels: bug (soundness), good first issue
