### ISSUE TITLE
Fantomas is unable to format valid F# (.net 6.0) program

### ISSUE THREAD

**Issue by KarolBajkowski** [fsprojects/fantomas#1969] opened 2021-11-10 18:09 UTC
Hi.

I ran into some issue while formatting one of my programs. Below are details:

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXATgTwDqdwDsIIs8DiSqAKASnyIGIBLAMzADEB5LhyqiHT6NEheGz5UA7s3QALSSQA%2BYAPpgAtAD4wQijPlg%2BK9dt30KkADTgoAZ0Tp0zQgHM7qMAG1bEUAKgAEnRsAAdkNEgXdGtfEkhAgDcAQwAbAFcI7ziqAAYbAIhIAEkxUXQAZWYAL2QCwoAWHLAAXTiAX3q-ZoSQ8M8owhiu%2BKS0zM8fQrAARhGqSABZZIAPABkXRDXRV3lY6ZmAJlzmtqpOuP8BXrCsyAAjWFhU-euxjKypwsP5%2BIrEAC2zDgqVghAAgugAKJiLisDaEOrNCCsNIOU4dEZXBbBW4DR7PV44lIfSbIsAAZl%2BRQqoWS0EQACFEKxYJhEAAFZKYZIAxyITBEgRYTIY85Ynq4-qRAkvX4JEkTNBfAINalQWn0pkstlbWBSAXQZIOUqJWBG5xgoVUEWIMUkC5UbGjPp3WXWoKKz7kgCs6sgmoZzNZ7IAqqFwpgjSbCGaLcwrerUal0QEzg6JQEbtKoO75e8ldlpgA2f2B7UhxAAYVSxrsVbBdhF0HQbI9KLRdrTmMuktd%2BKecslXrJ0wA7GW6UGdezFoD7gL22Bk6mBOmII6SM6ilK3YOPQrxt7pgAOSda4O6hugwhLlddtc9p19vEy-f5kfK8kATnPDPBrDoAKDYAgCyRLra9obpmbz9m%2BhIfkeo6FDM%2BTkgGU4Vrq-xAiCibkveUFgJu3RZruA4IcOSFfgcczoeWAFAZgOHAs8%2BHTJB3bir2ZFwbm75UaSNEoT86GlEgQxcIQAAqOAAOqyHId6dkRJFgNuQR8Q8AlkZ%2BRYoVS9GYeCmCwOkYgACKIKkzBAkxEGYKKXEZjxsGvlA0QHgWx4oWq6HLCsxSsNJciiFCKaIBUchsugCnwHs6oNCcznQa5OJaZ5iFCfpAQzH6-mrKUrDMCsXCRskraYFCKyhOydh2Amt7qj6yWPtxz68e5gzDIJhYqgIMylgVKwAEqIHAmDwHFCXkklqkwelXWZb1Pm5ROw1jRN8AAHLpACC6YHCxRAQCHjqjM81pS6XUAukqTODZiIcGyYFOAK0l4llfXkjMZ7oZtbLwIsd0PZsz2YK99n%2BtAcjcvSTGqDI8VKZdHVuTm3VeXp-VUDMv7DSZPLYFwmAbE201KYlrVUOuxELddGPLbp1E5QIxz%2BgFhPJMTpPME2u37QKR0nWdP2o1uL4Y7d93MI9iDg5D72fStyEBIcdHTJAXM82T6DAzLcsKxVUPoTDcMtgKiPMMjkDi6R6N3EzbzY%2BShyiZrAUAGpHoyLjiG4FNLie1MkLTakadmjtDFjLM4yQhyGR7qwcOZLaNb7YguK4gdU3b6mS1HPXM9lccQIcflJysFmwOgADijjVbViD1Y1Oe%2BiHEBh-TO5aXmKvCWr%2BUeyDsubIyoLQAA1oyPJT44dhSRUvLVs8e1NQRKkpXTV0911ffF990yHENmvbYgUhy8y6AGqIH3hFZxWELIjXgmIc6C5govTIRW-hwXFFDgPqtNm61NYAGlECIFCEFEKohShLz5AiJE39N5tRcmjRajNo5fWAVQQ4f1K7hSBHYOQbdphzV-t3TSe8dLO1jq7fGmsqhuFSIgEyrg9rlDkoge4iwEDIMKD-NBqUMEMz3JRIBqsBAUjQprcENlXCEBToQNOYIqiKIqukdk0lYDiXKBVRqykIp5wjuReCgC6El3JBSDWhQtb3QFIQAxiQ9RuHfgdB%2BLhn6NiMauGmT4JadQxvvSxh9CgUndnY-WzgkFrF5PceAyQaywAam4M%2BF9Ni%2BIfP49qgSHYAJjlY6YFJE52IsnzZI9xWFEL5nICo2AhirCySY-%2BkRRDwDhEgioIRWGFLCQECkFc7Ewg6fCTJ0NMCpFYLbShO9qHBNocSehxSh52IgVAvRQxSgz2SCoymG9jGzNEbvBZEjQm4JIBSE%2Bdjx67MnkguwJkzJiDPk2RAQMR5y0bnVBqPj1ScWEdvY58zxEWKWUU8JoCbnckvOycpdhoCYFsi4Cq7zQxPzBFZaAtYeSWnXigw5gK-5BNBX0i5EAKQELsd0pFLY%2BFIGab-WwLR6hRDsBwBqnhCLtCAA)

#### Code

```fsharp
try
    try
        ()
#if FOO
        ()
#endif
    with
    | _ -> ()
with 
| _ -> ()

```
            

#### Error

```fsharp
System.Exception: Fantomas is trying to format the input multiple times due to the detect of multiple defines.
There is a problem with merging all the code back together.
[FOO] has 4 fragments
[] has 5 fragments
Please raise an issue at https://fsprojects.github.io/fantomas-tools/#/fantomas/preview.
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1439
   at Fantomas.CodeFormatterImpl.format@416-3.Invoke(FSharpList`1 _arg2) in /app/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 438
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 464
   at Fantomas.Async.map@173-2.Invoke(AsyncActivation`1 ctxt) in /app/.deps/fantomas/src/Fantomas/Utils.fs:line 173
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
--- End of stack trace from previous location ---
   at FantomasOnline.Server.Shared.Http.formatResponse@95-6.Invoke(Unit unitVar0) in /app/src/server/FantomasOnline.Shared/Http.fs:line 95
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
```
            
#### Problem description

Fantomas is unable to format valid F# (.net 6.0) program. I was able to reduce the case to the pasted code. I tried to reduce it even more but I was not able to find smaller code.

#### Extra information

The used program compile just fine with F# compiler so I think the issue is in Fantomas tool.

#### Options

Fantomas 4.6 branch at 11/10/2021 15:04:59 - 8d864c36f95e468b3163e56e94277cab238f8795

Default Fantomas configuration

**Comment by nojaf** [comment] 2021-11-12 10:53
Hello Karol, thank you for reporting this issue.
I'm afraid this has nothing to do with `.NET 6`, there are a few bugs in Fantomas, especially when your code contains `#if FOO` kinds of things.

The short version, without a lot of context, is that Fantomas will format your code snippet twice (once with `FOO` and once without) and then merge both results together. In that last merge phase, things went wrong.
I've made [a video](https://www.youtube.com/watch?v=Z6y84Jsss5Q&list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K&index=4) about this in the past to explain it a bit better.

If you format the code only using the `FOO` directive you get:
```fsharp
try
    try
        ()
#if FOO
        ()
#endif
    with
    | _ -> ()
#endif
with
| _ -> ()
```

That second `#endif` shouldn't be there and that is causing the merge problem.

Are you interested in submitting a fix for this?

**Comment by KarolBajkowski** [comment] 2021-11-13 10:42
It would be cool if I could fix that bug! :) But I'm not sure If I'll be able to since it's totally new source base for me and in some places it's quite complicated. But I want to try. It will be great opportunity to learn something new!

I started looking into that bug and I found couple of questions about fantomas source code and design (I found one case which I cannot fully understand why AST was generated in such way). I'm not sure if this thread is the right place for asking for help/discussion? Or is there some separate 'dev' channel or some other way where I can ask?

**Comment by nojaf** [comment] 2021-11-13 15:40
Wonderful, I really recommend [the YouTube series](https://www.youtube.com/playlist?list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K) and feel free to poke me on our [gitter channel](https://gitter.im/fsprojects/fantomas).

**Comment by nojaf** [comment] 2021-11-15 08:22
One other thing I believe is relevant here is:

https://github.com/fsprojects/fantomas/blob/8d864c36f95e468b3163e56e94277cab238f8795/src/Fantomas/CodePrinter.fs#L975

used in 

https://github.com/fsprojects/fantomas/blob/8d864c36f95e468b3163e56e94277cab238f8795/src/Fantomas/CodePrinter.fs#L2026-L2038

`kw WITH !+~ "with"` will basically look for the WITH keyword in the entire synExpr range.

A better range would be from the end of the `tryExpr` till the start of the `withCases`.

And as the problem is a trivia one, you can replace the `#if` with a code comment instead. This will also be slightly easier to tackle.

```fsharp
try
    try
        ()
// #if FOO
        ()
// #endif
    with
    | _ -> ()
with 
| _ -> ()
```

[Example](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXATgTwDqdwDsIIs8DiSqAKASnyIHpGwBiASwDMwAxAeT4NKVCHSHM2iQvC5CqAd3boAFnJIAfMAH0wAWgB8YMRUUqwQzToNH6FSABpwUAM6J06doQDmz1GADaThCgIlAAJOjYAA7IaJCe6A5BJJBhAG4AhgA2AK6xAclUAAyOoRCQAJLSUugAyuwAXsilZQAshWAAuskAvi3BHamRMX7xhIn9KenZeX6BZWAAjJNUkACyGQAeADKeiNtSXipJC4sATEUd3VR9ySEiQ9H5kABGsLBZJw-TufnzZWcVilaogALbsOBZWCEACC6AAotI%2BJxdoRmh0IJxsq4rr1JvdVhEnqM3h8voTMr85hiwABmIHlWpRDLQRAAIUQnFgmEQAAUMpgMqC3IhMOSRFg8ribvjBkSRnFSZ8galKbM0P9Qq0GVAmSz2ZzuftYPJRdAMq4qmlYOaPNDxVRJYhpSRblQCVNhs8lQ7wmq-jSAKw6yB61kcrk8gCqURimHNlsI1tt7HtOqxWRxoWurtloUeCqgPpVP3VBQWADYQ2GDZHEABhLIW5z16HOSXQdDc32Y7HO7N4u5yr0k97KuX%2B6kLADs1eZ4cNPLWYJeop7YAzWZEOYgbpIHvK8u9Y99qpmAYWAA45-qI0bW1DCOvN-3t4P3cPiYqTyXJxqaQAnDerIwpw6Ciq2oKghk65Oi6u55t8I7fmSv7nlOZSLCUNKhvOtZGiC4KQmmNIvvBYB7gM%2BZHqOqETuh-6nMsOE1qB4GYIREIfCRCxwQOMpDtRyFFj%2B9FUoxmGAjhVRIOMfCEAAKjgADqSjKM%2BfbkZRYAHuEwmvKJ1F-uWmH0ixeEwpgsA5NIAAiiBZOw4LsbBmBSvxuaCUhX5QAkp6lhemHajhGybBUnAKcoUjwpmiC1Mo3LoKp8DHDqrSXB5CFeYS%2Bl%2BWh4kmaEizBiFWxVJw7CbHwcYZF2mDwpsUQ8s4zipk%2BOqBhlb4CR%2BQk%2BWMExiWWmoiIsValZsABKiBwJg8DJalNLpVpiE5f1eVDYFRWzhN02zfAAByOSgqumDIhU4Ggr4OqLCt2Wev1oI5FkHiOWiPDctB7iigpxL5cNNKLNeOF7dy8BrM9r17B9mBfS5IbQMoAosuxWiKCl6l3b13mFgN-nGSNVCLEBE2WYK2B8Jguztgt6lpV1VA7hRq0PbjG1GQxhUiBcIahWTGQU1T7DtkdJ2iudl3XYDWP7p%2BuNPS97BvYgMNwz9f2bRhoRnMxCyQPzgvU%2BgEOK8rqu1fDOGI8jnaimj7AY5AMtUTjzzs98BM0mcUl66FABq55sp4MjeLT66XgzJBM9pukFm74z45zhMkGcZm%2B1sPA2Z2bVB9InheGH9POzpcvx4NHMFcnEBnMF6ebLZsDoAA4m4DVNYgLVtYXQaRxA0cs4e%2BnFprEnayVvuQ0rexslC0AANZsoK89uM48m1EKDYfMd7WkZpmXM-dg-9cPFcAwsZzjXrB2IPIyscugppSL9MT2RVhBKG1MLSMuYuYFLCxkX3jHUutFxyny2tzHaesADSiBEBRHCpFKQVR17ClROiABe9uqeWxmtNmCd-oQKoGcYGdcYrgmcMobuCxlpAIHnpY%2BhkPZJy9iTPW9RvBZEQJZLwx0ajKUQC8NYCAMFlEAdgrKuDWbHjouArWIhaTYT1jCRyXhCCZ0INnaE9Q1G1RyDyBSsAZI1Fqm1DSsVi6xxoihMBzDK40lpLrMo%2BsXqikIKYtIxpvA-1Oq-TwH82zmK3Izd8ss%2Bq4xPnYs%2BZRaQ%2B2cSbDw6DthChePADIjZYCtW8NfW%2BewgmvhCT1MJrtQGJ3sQsWkadnG2WFhkF4XDyHC2ULUbA4wtj5MsSAuIUh4DInQbUSIXCynRNCLSWuzjES9JRHkhGmAsicCdnQw%2BDCIlMIpCwip49nGwPgcY8YVRF4ZE0XTXeFillSKPqs2RUSiEkFpJfZxM8jlz3Qc4Sy1lpDX3bIgcGk9lZt2aq1QJOo%2BISIPhclZMjbHrPKTEqBjyBR3h5DU5w0BMBOU8LVH5UZ37QnstAJsgo7Q70wWcsFwDwlQuGbciAtJSHOIGeizswikAdKAU4ToLR4jOB4K1PwZEehAA).

A similar thing was done in https://github.com/fsprojects/fantomas/pull/1914/files.
In #1914 a custom range was created that is closer to the actual token instead of the entire expression.

I hope this helps.

**Comment by KarolBajkowski** [comment] 2021-11-15 10:41
Thank you! That helps a lot!

Yes, something weird is happening with trivia (comments in that case) in combination with nested `try` `with`. Probably an even simpler case:
```
try
    try
        2222222
    // xxxxx
    with
    | _ -> 333333
with 
| _ -> 4444444
```
[Example](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXATgTwDqdwDsIIs8DiSqAmWu6-IqgembAA9PPHKIB3AJboAFjyoAfMAH0wAWgB8YAMwrVPQSLA9JMhWAAsho-p6QANOCgBnROnQDCAcyuowAbUsRQVCJAAk6NgADshokA7o5p4k-gBuAIYANgCuoe7RVAAMFj4xAJKESIToAMoCAF7IObkGGWAAutEAvtVedf6BIa7hxVG5cUmprh41YACMrT6QALLx7AAyDojziE4ifTVj1Jl1jVQt0d5TAcFpkABGsLCJG1QDKWkjNdSTdyWIALYCcImwhACC6AAooUAPIAM0WhCqdQg4KSNl2zUmRzuJy6YUu11uMT8CQew1hyleMRKQXi0EQACFEODYJhEAAFeKYeIfWyITA4qhYVJI-Yo9ros5Ym4k%2B5DNBPXL6Em%2BMkU6m0%2BnLWB8TnQeI2AqxWCa%2Bx-bkkXmIfkkA5UVG4zoiq5ioX4yXpUYAVjlUAVlJpdIZAFUgiFMJrtYRdfqBIb3fDEojcntzYL%2BsLuqKjRLHkSAGzuyCepU%2BxAAYUSWqshb%2BVl50HQ9KNcIRprjyMOQptKbtabxgwzowA7Dm896VdNPudOXWwNHYz54xALSQrb5k5iO%2BKuwSpUSABwD8le5UM8u-QgTqeNmfNy2t07t7Frx09moATl3iv%2B4PQnPLHw%2B8QnJrNOdE2ONsVzvB1u0JUYxmyIlcz3fMVXeL4fkjIkz0AsB5zaJNQKgVN70gzdoImOC83fT9MGQ75rjQ0YAKbAUW1wm8wPtJMHygzYXjggoinQUFCAAFRwAB1IRhFPBtMOwsBFygZd8NXCCN2dTYlFfSl-kwWBkkKAARRBEgEL5KP-TA%2BUYhNmJA1ioAiTtOOIzZZTg2Z2DycEhOEVYgRjRASmEel0HE%2BB1ndfQdisoCbLRPCekiQjVOlHwxjdNy5gKcEBHYUFA3iGtMCBdgggZKwrAjE93RdKKLyYq8WIxezeiSp0UqoMZswy9gACVEDgTB4FC8KiUimTgLiuyEscoi1NyMZ%2B26vqBvgAA5ZIPjHTAITyT8Phcd0xnG2LrSmj5kkSexjOhAAxelfzsTkhJvVrH3mnc4OW%2Bl4GmC6rqWO7MAesyc2gYQWQpSipEEMLJOOhrbKa6bXq4%2BaX267TWWwUFMEWSthskiLaqoWcsIm06kYclHnNybYc3czH4mx3GBErdbNs5Ha9oOokjuismTqXeLzsugRrsQQHgael6VLaolqFI0ZIEZ5m8fQX7RfFyWCpBuCwYh6tOWhgRYcgeGF2vSmWtlt6fFoem5gANW7KkHHgBxHAJict2JkhSdk%2BSOimqmbdRu2NO6m69OrSrXcKD2vaJ82cMRs4Q442b2pIahXKV9z9NgdAAHFbGK0rEHKyrE6JGrk7ky3bXAjPkvl9K87%2BsWlipX5oAAaypVk%2B9sKxBJKNki2uDaqvQ6T%2BYDhvb3Y44nLmu2uqV1bED4cWaXQdVVmekJDOywghEq-5ChHDnMB50YMLn8mhamgjQ5pu3FqVgBpRBECCTzvNWAUMe7IoQwjvrPOq1kEaTStolV%2Bq8aAfTznMPyXwrDCGrqMMaD9BYKXii-ZuctRjUHRkrMoThEiIG0o4DaqwQqIHONMBAYCaj30gTFaBFNG5LzRCvLOEAlCwSVv8YyjhCBR0IDHP4ZQxEFWSAyISsA%2BJ0IKpVKS-k66B0UhcZShDbZUCUIrGoytLqckIKo2IqonBXy2sfBwZ8KzqOnCTS8FtGrcJmi3UYSgeLt1FqA%2BYbJzjwHiMWWAFUnCb23ksJx54XH1TcanReniiE1BUDmfSrN4jnEoag1mwgSjYGKHMWJmiF5hFWPACEoCSiBEoSk-RJAlC52MSCKpkIYmg0wIkcEZscGcKfkjAhy9M5EiUG3Yx39f7KOKAUAe8RJGExnho-piSYEeOpggpp69jHdwWb3UBVhtK6UKJvSsiAfod3FmXMqFVHHugYuwgWAy8HP10SMrxaSP67JZEOBkmSrDQEwCZBwBULm%2BlPn8Qy0ASysgNNPcBKynnz3cckzZ-DlBIOMbU4F1YmFIFKXPSw9RqjhCsDdCqrgMJNCAA)

`// xxxxx` comment is duplicated

But what is surprising me the most is why on typed AST we get `Const (1, type Microsoft.FSharp.Core.int), val matchValue,` node when there are no `1` constants...

For now, I don't have an answer for that but definitely, I'll investigate it.

**Comment by nojaf** [comment] 2021-11-15 12:20
Hmm, I don't really know what is happening there. Fantomas does not use the Typed AST, so who knows.
The comment being duplicated is because the comment is found by the outer `try/with` as well.
The range of looking for the `with` should be more focused.

**Comment by nojaf** [comment] 2021-11-15 12:21
In the future, I actually envision adding the range of the with keyword to the untyped tree.
Then, we don't need to guess between what range the keyword is placed but can pinpoint it directly.

**Comment by KarolBajkowski** [comment] 2021-11-17 17:04
@nojaf  I created draft PR for that here: https://github.com/fsprojects/fantomas/pull/1971 Any help/comments/suggestions are welcome to finalize it! :)

**Closed** 2021-11-19 07:36 UTC
Labels: bug (soundness)
