### ISSUE TITLE
Insufficient indentation when applying function to list

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#2436] opened 2022-08-18 20:27 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBnAhgLYAOmYAvGAEIDaAggNx0C6kANOFLtlgJYB2Ac1yowNThFARpUACRYAnsWRpIArOwnTIsgG750AVxVitMgAwcZMyAEl%2BSflgDKvAF7Ir1iABYzYZi0AXy9Jfx1FZVE1J01vHX0jE3FvCABGUOtIAFl8AA8AGQFEAsQhLAALONS0gCZzf0CZEK0pLPklE0gy%2BAB5ADMi-kRnRUxqmz0DY1EU1NrMmwBRBwGhz38ISHR%2ByEbgzLbJyK6AI1hYdAntKaTZzbAAZkXte24AJywAMQEDADlEAB3dDFa4yLDvYz7ZqHcIdKKqc6XMFyRIzNBzbw%2BF5bZzEfDQRBURD9WDvRAABXw7yI2EQ7xREAhUO8TWkLRkRxuJ2iSKuLwS02SDwArDioHiCUSSWSSrBAfToPhuPZdLAlXxYPxGWBmYhoezYfF4WcLvy4WjhakwAA2cWQSWE4mk8kAVWIyneSpV-DVGt4Wp1-QM3ANEA50i5WxNvLNKMFdwxDwA7PbHdKXYgAMLoZW4LNa3DM6BYMlBkP61kHVpwnmIuMC27o0zWgAcafxTpl5OyiEIp3p5fQoarMJrxrrUD58abVtSAE4O1LnbKC%2BhA%2BLg8PK9Y2eGje1J5Bp43LfdrWlLA8HZ3EHR%2Blh6QXCIR8Dq9WGwBGwhPOrHkaeQrnjUGTXumK7ks4fa8HA67apuFaft%2BYBRnIR4nhaQFJheCxgbe96Pu8UGEDBlwbg8H6joa46Hn%2B9YAZhiYtjUzx4VKdDvLAhgOAAIogIIkYR76QjuMh7l%2BB7HHRUDqDOZ7YTU2LXrkeS2P0AAqFRlM4FRklgADqvDwJUOoNFR%2B40VJCIybEgFMZi1hpGKyn5GpmllEs246XphnGVU4o2mZu7VpytbSTEGh2c2DkyGkdouap-D9LweS9J6%2BClu8Sx5MQ5K4LgAbwQ8rZBWJIWRmF1kRXJWHMd4aSpglABKiBwO88C%2BSZ4o%2BKV0jichqEROFslRXO9Xts1rVkvAfyGP29IDLYj6ECI4ppEhkncuFhCGOgfAgsMXxkq%2BWCEepf6jcB9WLteLVtfA2S7ftxRHe8J1Cfa0AVNSBKEQA%2BoCRkmRtllbVVI2MdFDz1PaKkcTSCi9O8RRFp1-nFb1ED9Zt0ZHhDxryXV1i1KB1o5Pk8P4IjyO8EWs3ze8i3LatDzreZEmg7j21PbwB2IK9730udUSXQp3i1LhZOU9TKNYI9e28y9x0ZR915fT9Jb0gDQNVCDoW-uDtmQ2NxOsWTKkAGpClQAjwAIghozqJV6xVBtdPj7SEzF0i1Ep5v5F83EloVNsOPbjvdZjATlT%2BtGG5FxtXcTzn%2B3kPGwFgADi2DZbliD5YVEcYy7sdWaaDEE7V3sQLU8XmzzfNUOu0AANZUDSrfYLgvT8M4tJrnNRXWluI7BWO%2Btx%2BX5qV-Z0ONWTALAsUxJYAqZTC4gfHJfwvCavwdAOL2DMs9alFj9RE9l-%2B0%2Be1X0MTVLIKCPwgf8MHWquM-GWGOS6mwPYjgsAZUKkOUeZVx6u0ntfGqs9rS1Buo-Qi-BgG6DlEII%2BA53hbwELvQqJ9Ugj1En1GOKFKpTxgVDa0jwrz1wVusAoRBTjwHwDmWABUhCLz5qAohWMSGDRjPRG%2BkwvYPEeKTVIkBc70l4IQMoQD0AAGlECIGIAAuR9h274DfujYeiF2YDTIdA0WRMZCPElhIpuWiW7rFwBxLiDgARFkQA9BuxRc55QKoWYSLJz4WUvmDchxjq5PDNhY6kEFN602gO8GRvxHzwFdDvLUfFoC5hpHvbhJdSFuyMYnMW1hHh%2BwkVImJsinAGFGJxQwRZITEFGAocYCFtxZP4XjI2M9KGpEeCnCRSiVEqXppggYlj%2BDWOKPg%2Bq5go7Y05mhcKGEOkm1MXXCRlSYJywQBsXRzT9GcGYF4NQuAvgFVEIQkAQQgA)

#### Code

```fsharp
let sample = B[A;A]
```
            

#### Result

```fsharp
let sample = B[A A]

```
            
#### Problem description

I'm not sure the online tool put the right output into the GitHub template? What I actually got was also invalid, but for a different reason:
```fsharp
let sample =
    B[A
    A]
```

My original example was `let sample = A(Some(B[A(None);A(Some(B[]))]))` which also displays the problem, but this is a much simpler repro.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-08-18T10:03:56Z - e29a890b262dbc9a41a5b68bbe983252d8231a54

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment] 2022-08-19 15:57
Ah this is actually a duplicate of https://github.com/fsprojects/fantomas/issues/2392
Adding a space resolves [this issue](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBnAhgLYAOmYAvGAEIDaAggNx0C6AOgE6sB2mOBJmACqwA7hWph6TZpAA04KLmxYAllwDmuVJIURQEA1AAkWAJ7FkaSGqxzdByEYBu%2BdAFdLOw4YAM87w4AklxIXFgAyioAXsj%2BAWAALPYQzPYAvnF6ycZmFtrWYXYBji7unjTZEACMmd6QALL4AB4AMmqILYgaWAAWRfFVAEw%2B2amGGfb6dSbmnpBd8ADyAGZtXIjhZpj9hiWuHtoV8WCDtbsAoiEra7GVGMuQo%2Bm1U7szeVYARrCw6DsOzn25TuAGYzkEuEp2FgAGJqVwAOUQInQ7X%2Bhiw7A8T3GL2yjlyc2%2Bv3RxlKBzQR3iCXBEEg4WI%2BGgiCoiGWsHYiAACvh2ERsIh2KSIJjsQExgYJoZXgDCfliX9wXsyoc7gBWWlQBlMllsjkdUSC6D4JTBJywY2qWBcYVgUWIHGSvHFd5En6K-GAlWUu4ANk19MZzNZ7M5AFViBZ2MbTVxzZaVNbbctXEpHRApQYZXTXfL3aTlRSvPEAOwB7XBvWcgDC6BNuGr1twougWA5ydTDvFz0mnrlX3zSq9RapAQAHOWg7rQ4h6ohCJ9BR30Gnu7jey7%2B1AFQXh8DjgBOSc6kP6xvoJOalMrrveCUZ53TLeQHdD8n7gZ%2BO6BnV0ZZYQVG0IQh8Fte10zATMsk3WY8xJN8gVVY4qhqb8K2nfVwnnFQ4AvG0r07CCoLAbMclggd4M9d8kIGU40KnP8APYLDCBw35LzucC1ydDcn3I7dByoxCfWQsF6N-dhYDcEIABFEFRVimLArFb0Me9IMfN5nxsXdqJEgYaW-RomkCZZBB6Lpwh6DksAAdRUeBeltEZuIfXitP4gpbAQ71iwCKoNSM5pTPMrpzhvKybPsxy%2Bk1X0XLvHtpT7TydJ8kc7iqf0gpMrhlhUJpFijfA23Yc4mmITlcFwRN8LuMcErUpKsxSj4oDSoTfNHbwqjLHKACVEDgdh4GipzNQSRqDHU4jSIJVLCnSj9-InAaho5eAETcBdBRWQIAMILRNSqIjNNlTzCDcdBVFRdYYQ5ECsCYwRYKWmj-KPb9BuG%2BB6ium72nu9hHqUgNoB6XkmSYgB9EQHKc073POtqvN04S-O8YYA2Muh2D5UxFnYNpmzG2L6qmlJmugviUY6l09IxwxBlQ44GmaXH8cJ4msC2nb2D2g6jsyxHkpglHLuulRbsQIGQcFF68je-SAkGOjWY5-ACaJlRmz%2ByXpdlkrQe-cHIdbQVYfhvoRZasW5jp6YGe6pmxNZ4yADUgSoNR4DUdRSdtBqbepjzacWzqMuOQZDLd5oYWk1tau9kI-YDiaKbAGazpzbTw-p9HnYMQZAtjpoZNgLAAHFsHKyrEGq2q0-J4OSNat1KPzrq7kGbK3f%2BqX2ioC9oAAayoPlR%2BwXBFi4cJ%2BXPba6uOa9V0S9dRZp9uPU7yP4kGPrWaRFFB%2BwEREC6BXEDk-KuBUK0uDoEI5z5oXji4teeI30Ot7Rruo9W9WqJ1BcHjlwRO1pIjAJKm4TkwhgihCwCVWqy5V5NXXrbTecFt6OwLt3T6gCmJcCQU4A0Ghn6LnYNfNQd9aqv3iCvVS00qatztlg3%2Bu8Aggi-H3SWNwWhEE%2BPAfAtZYA1Q0EfaWKDGGU3QSHZGP8laMwMCCFm8RIC10FCoQgXREHoAANLn2IPAnRwRx74DAWTZehFXIaSRjnTyr4I7LW8CCNWaih7mJHjcXAuMpIhCRM2RAv1%2B7S1rlVGqTZlJig-m5L%2B8i2GKMLhAEErt3G8lPJyGSOtoDsC0fCAC8Awy32tHJaAdY%2BT3ykS3OauYKLYLeE7UEMc1EaNydosIrhNiSTcM2LExBNimG2ARG81S275Adg03BxwQQlzUQYxAxBjK8woSsDxXAvHtDof5HwGcs52LIijRxO9nGGBBL3NRXScJYHqAgW4ViRk2LSAoZgcRrC4BhDVbQDCQBpCAA).

The parser is actually considering `A;A` as a sequence of expressions rather than two elements of a list. This is due to the new F# 6 index syntax.

The bug of this bug would actually format this as:
```fsharp
let sample =
    B[A
      A]
```

Which keeps it as an indexer expression but corrects the multiline indexer expression.

**Comment by Smaug123** [comment] 2022-08-19 20:17
Ah right - yeah, I can imagine that it's impossible for Fantomas to know the right thing to do here :( I wasn't a fan of alllowing the omission of the `.` in `A.[x]` in the first place!

Feel free to close this as a duplicate; we'll just add the space in.

**Comment by nojaf** [comment] 2022-08-20 13:12
Thanks

**Closed by nojaf** 2022-08-20 13:12 UTC
Labels: bug (soundness)
