### ISSUE TITLE
List literal argument violates "avoid name-sensitive alignment"

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#2189] opened 2022-04-05 06:43 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEA2iAuYCGGGAwgogM5gC8YAtgJ4BiArgHbTYCWsLYA2mAB1IAM1iwARngBOQgNyCRYyTMjyhoidLkKNy7eqVbVOwyrABdSABpwUMjk4sA5mVR9bEUBG9QAJNjoAB2Q0SA4WbGsPb0hfADcCJhD3Hx8ABhtUmIBJFiQIgGUOAC9kTKywABZoiHNogF9yzxq-AOC3MIiorNiEjCS3XhaIAEYm1MgAWTwADwAZcMQ5xGdsAAtuipGAJjSWup9G6K8J-yDkyBX4AHlhBZZEAoCsTZ9exOShirBt8beAUTyt3uZWGUAwwkg%2Bwa4xObzO7VC4jEGFeMXiH0GYIAzH8cix7FJsAxwgQAHKIADuGEWaJ82CkSWhh1hLVibQuyNgqLx736nzBlTxEEgBUQNA4cAw3AAgthATc7rThWBhAR7MzvEcfHD0RyOlyeWyMfysd8AKwq0WBPDQRAAIUQoikiAACtI8DQcIgpHTvAymVkDlrWT0EZyUX6%2BQM0F8KgA2K0FG12x3OpawSk%2B6B4ey5OKwHOcbh%2BiABxCaiDa7y6kXhg2R3kmmMpCoAdiTKYdTtgLoAqoFglIc3mWAWi1wWKXVeqK0GYcdjfqkY3jX0W3GsgAOTu27vpogYXNkEgEgPsXvTtUYDXzlmLsPLqCGqPNgXfACcu9TPZdk3F4g%2Bles6VmA1bNI%2B5wNtyr7ru%2BWwZGC1p7mmvaICQ0pTiq163qkwZVqGpxPpAL5NnBZpbGMSHJnuMrCNgPokDQNB4NO5ageBYC1q0UErjBZGYrGYI7N%2B%2B5oWKEpSiW2EgXeIYPkRvHPquYbkUJ3wjLi1FdnRDFSBJkrctJYLsXJBEKfCxGkWugmtlkIxCkhuT5Ng1wsAAKlIdAAOocOswE3nOeELjqS5KSRKmnGpdmpCMlrabRUiwKw8AACKIDSEp6WxjJBT4%2BFgYRlnheEkQCaa6lbImSHTDM2TCO5awrP8gUFGsvbYL58D%2BSqlR7GZhUWXqJVdOVG7CR2NWzLkwgcDM1xDng2C9v8MyBC6ZBkJO07mv1wX3qFkGIlApWwbZm6xTuU0zAASogcBSPAXU9YKe35SFNZhcdnRlTZFUxT4Ixftdd0PfAZJMDQgFSLc2QMTQrgqiMHFFcN300EwGCcDSDwML2LHYHp7lQWN8FZLsVqg728CTJj2OLHjUgE9lVrQGsHrsD6AD6lIcN1Gwo0NdbEadpMUeTVHfFMswylIUh4HQ1xSAsZCdXzL3fH1guHYp32i3943fNsvzXbL8uK8rHCqxDUM%2BrD8OI8J2ufUdFwY1jHA44gjPMz6xPtGLlXk1pUtmwrSsq9gtMe17PtLSzSFsxzek8%2BrAsDZx3HsiNv2qedYLbI5Uu1QAah89rhPA4ROM9Gwqlub3eAVmdfRc%2Bt5-9F0%2BNs8XF7MzBsMWLAV3k1e19OWsZ6jws52dncF9VfczKlsDYAA4jgq3reQW3cOPKq7c7EG6xG-EG2TqTbJNxd057iz2tK0AANb2vLz84GQbkFJ66HcpDWFghwnlJuH1j7FW%2BtZDuhsKjbCulLCk1J744CzCsf2iB0qzRYH5ScMo8j-ltlIR23wgFHy4q3aCRooEX27sDKWABpRAiBAj1UaisXI38vQggCrhd6B0XYnw6O3KK%2BdvjYkQkvFqEoyBrH3q9UhWd6x8UocI%2BeojJYVFFNXLAssnCQxWJ1RA4hJikG4cA2ooCyGuwoXPaBWRsQm1DjSJwLAB7sEnEUZxS0mAuncrAZy%2BilrbRkoFeR5ClE2Ood4bEIcNEyixj6FggS4gZmcPg6GGDwjYO4EQioJCp5Cx4hAyK8JopdyiUXDR0dOAgjmJ6cQ8A8CHlgFtZwCCvamNCVY8JgcAZRN7ho1KVs8DiCwJIq2awCh0AiLMDp%2BSdbgNPsokpIiKjYkXhohhTD-ERFyK-PAbA66ANkvteS8y0aLIieLVI2Jr4aIfvsp%2BIIyCy2SnkCkqtEA01vl7LeG1d4EhyoGE55kzkzyKWfKhVyfDYjgXc6QqEXSDLINAKQHAJSJIYvAPsWDuDpWgEeeWQ9ZnAsGqCwpFyellIgNiWhGibp4E8UlJ%2BxLeGnP4Qs6xlLXpJgZJKKOJjgk8JAYcWw5hyhhDIAwLabgSH1CAA)

#### Code

```fsharp
  let allCodes = myFunction [ "foobar"; "foobar"; "foobar"; "foobar"; "foobar"; "foobar" ]
```
            

#### Result

```fsharp
let allCodes =
    myFunction [ "foobar"
                 "foobar"
                 "foobar"
                 "foobar"
                 "foobar"
                 "foobar" ]

```
            
#### Problem description

This violates the "avoid name-sensitive alignment" clause of the F# style guide.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-04-04T14:08:13Z - e784cd68954e7c6fac13ed723d108920d04c1ecc

Default Fantomas configuration

**Comment by nojaf** [comment] 2022-04-05 09:13
Duplicate of https://github.com/fsprojects/fantomas/issues/1826
Use `fsharp_disable_elmish_syntax=true`

**Closed by nojaf** 2022-04-05 09:13 UTC
