### ISSUE TITLE
Inserts unnecessary parentheses

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#2855] opened 2023-04-20 12:45 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBDAdAWQJ7cQBcALBACgCMAaMAMwFcA7MMgSjAFoA%2BMaVyKuCgBnIoQCWjAObDUYANpCIoCKqgASQrgAOyNJEmEBS1ZHUA3dABt6ehSbUAGQWrWQAkoySNCAZXEAXsgurhAALA5gALomAL4hypFmWrpyBj7GoWaWNnaKoRAAjAmukNjoAB4AMpKIVYjSJJkFhQBMjpExavEmKqWaOnaQDfAA8rQ1jIi%2BWlbBSRbWtnL5Ba0lbgCiXuOT8wVQVrSQnXElfW4DqfoUsLBWzZc5y2iroQDMG6aeogBOhAAxSTWAByiAA7lZao9XIRfrZTt1zgsUkNbvcYRBsks8pFwl8sb5tOhoIgAEKIWiwX6IAAK6F%2B6AAtkREL9Mao4QjQl1VD01BdTFc0XcHl9sbkVniwABWAlQIkk8mU6l1WDgtnQdCiTzmWBaiSwRgciBcxCIvnIrLCtLosULZ64g4ANnlkEVpIpVJpAFVtLpflqdYw9QbxEaTXRrKILRB%2BapBVibTdRRyJS97AcAOxuj3K72IADCVm1wkLRuEXOghGpkdo0fNPLOvRRg1tqfFi0lr2lAA5c8TPSqaQQmRQ2XWG7GwPHEtbUe2MZ3HVKDgBOAdKr2q8tWCPy%2BtWGNNpEt%2BdtlNLh041ctZzS92DxAAQVohDZ5aZTPQkbN09nYCJhoC6Xva1orj2ByFMUD55tuNK%2BIgTLiHAe7GgeU4npaZ79CBUB2mmXYZm8rhtJupKvu%2BvyIchqH7tKf5YXGVq4Re%2BEdte3aZi0nywU%2Bz6-LATDwAAIogULIVRv7wo2ri8sxOGXHh6RGMuN6QS0YRuuUFTuLQAAqxANL4pD-AA6uI8BNPKHRMTOLFKWxKmERB3GhIUcoPjpemGQ0mxHtMpmEBZVnEJGzq2XJzYCq21xQIYLnqW5pGul5lSeLQ4gVKMAboDWvybBU2g0sIwjhuhfaRWo8n2YpQrKQlalcSRaiFDmaUVAASogcC-PAIXWdKYRVaoNUAUByROY1nHEdKhT9h13W9fAIL0GObLjO475MrI8qFP%2BDn1U5TL0FYEhQlMALUt%2BhBUfpbZNbNUEbg%2BS3UvA2CnedtRXb8N1SW60DEAyJJUQA%2BuCllNAddVJg1GSPU6az3gcZSVAJjK4KMvw1JWA1hfKvYjRAY2HXDU0IzNSOhK0MGozpGPoFjOPiJWq3rb8m3bbtc0wzF55xZAJ1neIF2IL9-1svdqSI7eNPrA%2BjPM7jhCfSLYsS3lAMPkDIPVmyENQ2FfMJrFQzTeBSUtaorS8fTlQAGo4mSkjwJIUj45GRMm3OrGCxb-SudbECtFpHUAkw1blS7Xju578rDT7gFm2kAdPFb0qtJ59sVCJsCEAA4kQhXFYgpXlfHlVJxNybsVelvNZnqWo2CkK1BShAag00uIGJmWMOIhqMM%2BXijuOvw8wcjFRae-N%2ByK9eBxnBytO1qPPlCUiMBHjBR0a-hb3l9A0vpsCeN4hB5eVk4BdXKegYljcrwt69nWyjBX%2BYarSGPbJ95Ig9yqTwKIeY8M9sJz0coLAissNI0xevTL64g9hVGZBQeA6BiywDKtIVuYsb5gOqtFU2AsF5gSXk-Ao7wUYFEgCXNk4gWQ%2BGsAAaUQIgbQ58GiEE8GSRku8CbSlAbJIhs8SHz0XOQ9OlCPh01oWSEsjAADWexhACSEl4MElZEAfSQWLEuJUyoVmktycBClIFHWgRxBuT0qEK1RmSBk8Fe6s2gL8RhwJ3zwB9API0YloAlkZEPAhIjRrEN9lAoYwtvpTD4SSJRRAZi4DmI-WxHw7a0LVjE8kjJoAJL8LMfYtC3HMl0PAE4dlxr33ipTGx1NXDvDDqjNhHCdLs3HuMBR6BlGqMjIURwxNojhOTqQyRqT6lqHeNnWheD27DkQFk0WtRPzaHoJfIeBiy5GIqlPGSd9RkP1gclSZzdaH0PcUwy%2BVh-LIWEIIg4wj-xCCiCEAwwgARlTkI82IQA)

#### Code

```fsharp
a.MyMethod(b, fun () -> c)
```
            

#### Result

```fsharp
a.MyMethod(b, (fun () -> c))

```
            
#### Problem description

The parentheses around the lambda are not needed.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by AsmusAB** [comment] 2024-09-17 08:34
This does not seem to be the case anymore. Unless a non-default configuration is missing.

**Comment by cmeeren** [comment] 2024-09-17 08:38
Seems to be correct. Should it perhaps remove the parentheses if they are there, though? It does not do so currently.

**Comment by nojaf** [comment] 2024-09-17 08:39
This is a duplicate of https://github.com/fsprojects/fantomas/issues/3082 indeed.
Fixed by https://github.com/fsprojects/fantomas/pull/3119

**Closed by nojaf** 2024-09-17 08:39 UTC
Labels: bug (stylistic), good first issue
