### ISSUE TITLE
Unable to format F# 8 extended interpolated strings with curly braces

### ISSUE THREAD

**Issue by stefan-schweiger** [fsprojects/fantomas#3028] opened 2023-12-27 14:24 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPMAvGADqRaIDOWpxAdnZjrgIyFgAk7NkpwwuAXwHcatRngBMbTiMhh%2BaPoKEkeahtjwBmaV3WRci-kOADV3SABpwUCtiwBLWgHMKqMAG0bEUBD9R2LABPAAdkNEgnLCtvP0h2ADcAQ3QAV3DPWP8ABmt-f0gASVokWiwAZQcAL2Q8-IgAFiywAF1YgTqfZvjgsPdIspj6%2BOS0jK96iGZO-MgAWSTcABknRCXEFywACyHJ5gls5rb-DtjfWcDQjMgN%2BAB5ADMV2kRy4MxdgsSU9PcJyYkMwKAFESo9nrVmhBIOgHpAju0Zucvr1rgAjWCwdCfOLfMZ-KFgLRAuLFOwAJywADEnCkAHKIADu6FWOP8WHJ6QRJyR3UufQiGKxbICo1%2BaH%2B9QaJOh5RCSWgiAAQogHrByYgAApJclJAC22EQ5JFEA5XPqxz8p38yNxqP6QuxJJGP3GhIArDKoHKFcrVeq1rBGUboEk7MUErBQ45YLQTWAzYhuVbecN%2BejMU6%2BWK3ZMwAA2L2QH2KlVqjUAVRCYXJofDtEj0YcsfjDxSdmTEGtflt0PTDszIpd%2BIlhIA7EWS37y4gAMLoMMUWexqic6BYdWt9tJi2Is58%2B2CwfOvHizJ5gAck-lpf9GrmiD1aKNW-QHd3PP3acPUEdQ9PuaTAAnNevplgGy7oC2Xptm%2BO75JaXaphcP6QH%2BJ45gSebMLkhLFjeiAAIIPOQ5LLnqepJPGiadmA3ZdN%2BVwDsKGGulhezTHhU7gRq5SPg4cBQXGMHbrR9HyAeTFHix2ZsaO2GAlxBHEaRfF6gJWLQYSNEfimX4oVJv7HrJI7nnsxJKb6hHkrAqQlAAIogLLqaR1GcvB-iIXRyEooZAzRKxpmSvkzDSnhCy4IUDwACpbBs5RbOqWAAOoOPA2zxoculIfpvkClAUT-ph8l7J64WLFFsUbMCcEJUlqXpTsXr5llCF7jakn5f5RVyWZ9TMIW5WRbQDwOLgdw1kkG7ksCuAhBqFAUM2wmEherWee1PaddchWBWewX%2BMwE5DQASogcDkvADUZV6DTrX4Xnib2ASobtJn7YSzBXqd53qvAdKpE%2BRqPIU5B6m4XrMGJPl2n5eqpOgjgsi8VLqpRWCkdFTF7YB-UgXhZ0XfAcwI0jqyo%2BS6OuUW0BbDqCqkQA%2BoyaUZdDuWw11b1psVfX5AcRYRdZupBHc5IrFQ11Nat90QI9MN9q9gw4%2Bx9QSJxebzIswtJKL4sOFQANA%2BSINgxDn3sx1jFdfDiMOMjiAU1TRpY30KslWrimazresS1gJN2w7TtTdTeG0-T65GszrM7JbW3Wztyvvbj-MWZrEUAGqukqTjwE4zhS-Ga1xwxBlc0nPO9QdfgSGF6eLFSdnrstOclPnhe3bLrSbaXeWJwFyeq-zZX17g9mwFgADi2CzfNlBLbGHcyyXEkJ8xWaV0FhISINmsMsyqwqlgwYbK7iCOaNtAODGtCESUD7G%2BbeY6W1n5W2XGYyZvH15hIx3eyyZwtBG60GbrGSoQCpqpA1NFWAxRShYCmstV875X56Xfn3dePUt6-2%2BgA0itAkEJEDC4B%2Bz5yQXycNfZaT9JiwVQRtN%2B8cP5YPdnzfwEh8bp1Jg4CESx9RongEkecsAlouH3g7FBHkHo91Xiw6SG8Li82rhALQuFNazyNA4A0ZQUgAGlECIBCPAjYWBihKl1KA6WeZ6HSLlrI56PQ-LoUHh7fIWgNaTEgEqBctAADWEIKDWVsiUBkVBEDEx4Q7WeC0F60FofUF%2BjD0HMMwQo7BP9JhaC9l4pUOoeLnwNtAck2jaTkHgBWK%2BsZHLQAXLqG%2BUiV6OP7BEW2ZMXgWIVH47AbwggfDYSookacvEB3acqXU0BukVHeJCTWxT9RhHgPCbK3kOaKz8tzJRVdCRaDrl4gxRiIpG3IY8HxSR-GBPjDhLu8s1kvWccZb%2BKd-BaBHl4iRh87yIFGfbVY5EQipEQTfGJ89kFeiSTIphvdOaf0UV8ZROzd5eM0SUnRiD0A1XUhQaxdDRIrIEDYFodRIgUCpEtdwtiQACCAA)

#### Code

```fsharp
let x = "test"

let x1 = $$"""{{x}}"""
let x2 = $$""" {x: {{x}}} """
let x3 = $$"""x: {{x}}{} """
```
            

#### Result

```fsharp
let x = "test"

let x1 = $$"""{{x}"""
let x2 = $$""" {x: {{x}} """
let x3 = $$"""x: {{x}{} """

```
            
#### Problem description

F# 8 introduced extended interpolated string for which you can specify multiple `$` signs in front to indicate how many curly braces you need to surround your interpolated code with. It seems like fantomas does not support this syntax and instead just gives me errors.

`Formatting <Path>/MyFile.fs leads to invalid F# code`

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.
- [x] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 2023-12-22T09:45:59Z - fc341e88f36ab28c3331e0e6455a0f848bf44f33

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by stefan-schweiger** [comment] 2023-12-27 14:25
I'm willing to help to this, but I don't really know where to start and I feel like this might be a bit of a complicated change?

**Comment by auduchinok** [comment] 2023-12-27 14:46
@stefan-schweiger I think it may depend on a fix in the compiler: https://github.com/dotnet/fsharp/issues/16418.

**Comment by nojaf** [comment] 2023-12-28 07:03
Thanks for the report, but this is a duplicate of https://github.com/fsprojects/fantomas/issues/3012.
https://github.com/dotnet/fsharp/issues/16418 needs a fix for this indeed.

**Closed by nojaf** 2023-12-28 07:03 UTC
