### ISSUE TITLE
`SpaceBeforeUppercaseInvocation` corrupts underscore lambda invocation

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/fantomas#3081] opened 2024-04-18 00:35 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAMrNAIboCWsAdgAqkAWYAFAJRgC8AOgE4eXe8QIAG0Tow2euzAAlRAGcyAL0QBBLl2KYAPLABGAKwB8TZvz49KgsAFtE13Yi5gA%2BgDoV8eEwBmQ2LCc0ACEAVzIheDJKAHMAMT8A1k4LKysRMSFiOTE2cUkAH2MAZUQAR1drYmwXVwBxUQAVHEQWMEKwEvL0Lkx8LPQzVMEWSAAacCg5UXIYuVQwAG0JiFAhyAASLFx5yCj0MeXBDYA3YiEQ5DQloYgABnGbqABJSiRKdCKlZAebgBZDiAAXUOAF8fisAVBNs0dnsDmt1qdzpdFpCIABGcGpSAAWWIAA98FFEPhEDF0HR4Td0QAmW6Q4FWMGHVbY6HbNCQMnwADy3iJlEQRSwIipVhOZwu82uNxpWPFAFFXnyBd80VAhN5IAzQVjWeL2SjILp-EIxUdEZKUTKhgBmeVHF5TLjoWJRM4AOUQAHchMTzVZuhcdUy9ZCNlsjSbYGaHRLkdL1b8HRBIEUJNBEEFEN4AohaBpbOhHAHBEHECHBMyrPqLZGdtHY%2BHLQmruqAKwpqDp4iZ7O5rgk2DexwkKYvY5EUgUSiliDlysQauCWupw0N02l%2BNStuPABsXbTGazObzAFVsLguGPEBOp%2BQqHOwAuhoyq2GEfXOY2ty2d6jHgAdkPHs%2B1PQcAGFMjkOQIKobIuBCaB0ACJ8X1SN8lw-NkvygH84z-a11QADhA49%2BzzHE7AcLg0MQitX11Flm1w41NwIpF-xtVIAE4yN7E8B0QOC-FnLt0KsTCwGXCFPxhb92ObTiiMedF7nVI8BJUbxiy4ODrEqOjg0Y0NmLkjk8MUhFlMTVTMQ00DBLzEprDIOBRKMhiMKYmsWPkyyY1-Gzd2pOUHOPbTdJctyY0fcT6MXaTsINVj8KUq1bOpe1wq0rhYBCV4ABFED9VzdM8xKZLAVcoVYuEOIykKhnRZMNLxfEnm8Bo6DJIo6ACdAAHUyHgCkn3pEz3zMnD-N2d4gsagDqU7NqCU67qyQVIQpj6gbhtGykuz3CbvNM3zzKNer0tbJbmoPVaOsobwyHxHkr1IAIFXxbBBxgmcn2Ik7JJ8lc-Isub9gam7uKsdFgIe2Q4C4eB9rGrtfiBwQpKqmqI1mq7rMWmHBHRUiEcQJH4A9EJ7EcPknmLaw5i7dFKuSutZusEIhHIP1BViAJKnQXSmm2KGuPVdE%2BI0xGAngHFud54kBa4IXysPaA6GIDRkMcZxvRGsa2emlL8fm8WVNldTHlxAk1A0TAeS4IlslRw6SMxoEQdkmbwYJtlgtu1IaXsm32vtzQnZd9Bqdprh6cZ5nJeN87faNLmefCZXBdIEWYQtzKhhpMKbYjx3nbIbIFczvnEBVtWSw1rWdd0-XDcpFPQYu2FzeuiXHhpbKw4JAA1K0giiSIYjdgHPbAbH2bXOre8J6H1RpVrh-xWICuQmcJ9eKJohn9G54Xk2Ob9leA6J9eVq3wrYHQep0C%2Bn75AUKgT49zufdN8G0qr37rKe6NsvS%2BmJNmdAI4ySi0QMVZ6lAyAPkoCoV4VE45J0eBJLG3tqpgyjFZG%2Ba8B7w1Ln6aIlAd6UD3lQT4lDSAhEHA0WALw3joGnHFdU3gzhTF-vg7uClAoFyasHMm5DdKUGnMcIcMQME0QQVEZBM4sE3B4dtLywMzpdzThuYRfdLZF2lmHRWZBVR9HsPAYgUFYAKBiOA2uT51F8MmlhC%2BS9ZqAOIcAu01sbiQDfo4Mgth3hnAANKIEQNgNhZJ0AvCCBoGh7tHjOM0bg7Rf9L6EP0UAwxqRbSh38UETIlAADWqo5BqHyq8L02REDy1MbXN%2Bv1P6UFUUMHBXsMkCN0UIpsuTC75JLkU7WFFByFUrtALgwT3TFngGeJBVBirQEyBoFBTjeFpK6VNVO-906NMgTrUpohhSYFFCIoOVhbRD38dXJWgoEm9mOR8EUaobZTOINYXA8BtSuKSu42qZtIYGMGVcze-iIlRParHGifJinEDKRUp8akz54NxuuPpC0SE3FtPffxDjIHgUQHcrOgp9LYBCBwlBzSP7-XisZU6OydF7L0f07xeSrmgP8YE6ZISOFCC2q5OQyS1GbMqhMQEPxdhyFiAoeYqSQAgiAA)

#### Code

```fsharp
type LocationPath () =

    let path = ResizeArray<obj> ()

    member _.Add (floor : BuildingFloor) =
        let last = path |> Seq.map _.GetType() |> Seq.tryLast
        ()
```
            

#### Result

```fsharp
type LocationPath () =

    let path = ResizeArray<obj> ()

    member _.Add (floor : BuildingFloor) =
        let last = path |> Seq.map _.GetType () |> Seq.tryLast
        ()

```

Pay attention to `_.GetType()` became `_.GetType ()` which is wrong
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- The formatted result breaks my code.
- The formatted result gives compiler warnings.
- I would like a release if this problem is solved.

#### Options

Fantomas 6.3.0

```fsharp
    { config with
                SpaceBeforeUppercaseInvocation = true
                SpaceBeforeClassConstructor = true
                SpaceBeforeMember = true
                SpaceBeforeColon = true
                SpaceBeforeSemicolon = true }
```

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by nojaf** [comment] 2024-04-18 06:34
Duplicate of https://github.com/fsprojects/fantomas/issues/3050.
Feel free to send a PR for this problem.

**Closed by nojaf** 2024-04-18 06:34 UTC
