### ISSUE TITLE
Multiline string with `\` is handled incorrectly

### ISSUE THREAD

**Issue by bmitc** [fsprojects/fantomas#2601] opened 2022-10-27 03:06 UTC
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEIBtEBcwAd8BbMAXjAB1IAFAZgooDsGKAnJjTrjARgAYwAJgbMG7Rt0kRBAVhkiW4qZNkyhfACxgeM2kLnqtOvasPbd%2BtYM3mTB60YumHCsR2Vdjls1%2Bc3f9v5OgY70TIruHhh%2Bod4OtnFBdlZJibExrmyRUQkxuSH5KekFxgqQkAA04FAAzrg4AJaMAOY1qGAA2tUQoNyQACQ4AJ74yGiQTTiV3RgDAG4AhpgArmOdM5x8VVKQAJKMSIw4AMoNAF7I25IaG2AAujMAvlc9twPDo%2B0TR9N9-YsrNZdKQ8F5cSAAWQWAA8ADJNRCwxAtHAAC1%2Bkh41luD04zxmvXBgxGa0gyPgAHkAGbwxiIY7DbAYzjzJardrAlRglkAUQO1Npl1uEEgmCpkBxTzBhJZxM%2B4wARrBYJhmbN-mygcKwLRubN9nVWDgAGJNJYAOUQAHdMAi1ZwcKxVpK8dK3nLSUqVfaoBrARztRo9SLjvgFtBEAAhRBU2CsRDUBasBZEXCIVg%2BiCO53cXEYfGcGXqj6e5WqvWs-1oTncGTBqCh8NRmNxxGwK3p6ALOr7OawLuNWCMTNgbOIF35t1-EtfL3l90A9nV7UANnrkEbEejsfjAFVCJ3u4he-2FoPh-WqUs6hOIAWMEWRR7Z2WfZWl%2BspAB2deb5s7xAAGFMG7GpAKHGps2gHA4xHK9MBvXMpQJd0Z0VV8Kz9D8ay4AAOX8wy3Ft4whRAiAVdM4OvcckNdFDpxJF9vUwxctSkABOAim23VtwMwIcqIQmiuDzO8pyJNCoDnN8sLYzEtm1DdCMQABBKkcHTcCiCIBYRzHW8wHvV4GPlKSMIXTUAxBUFFL-Hj42OMiGjgfiL21eDEJE5DC1Qxj0OYiyq0-TFBC4iM1I01hHKIZyVQE%2Bt9Noyd6IkvyzICv5WKszFdVs5SVNYWBlgOAARRBbRiyK9KdYTOFEwzxNlSTvimFjLOXEEg0UqFoV2KkABVUWRY5UTjHAAHUGngNERz4AyjLAR9fWayYZKyjrMTrbqYT6wbkR5ISRrGybpvResVzmpKxJSpq0patb2uC7geDXbbesYKkGmhClRmTGDWB5aF8HjGoagaeLtVwy6vLonyTNJVa2qCnDOB4H83oAJUQOBWHgE6ZvrDRobq7yH180z7qR7DtR4fDMexuN4HNZZyPTaldg0og2nrHh5sa4s7qIZZMEaW06WNOMdJwSL%2BsYqm5OezjFKxnH4AhYXRYRCXWClqr12gVEk3DSKAH0rSmma%2BZugWKcRwLqakax1x6grkyGClWHhSD8bOyHiYweqFqW947rtzLHpR6IbJ2F3WDdj2vZwZnWdYdnOe5mmrbh1KKaFkWGjFxBtd19NZc%2BeXsu4QRQsU12Fndz2Gkg9X88L4uzz1xSDaN6D0zNi30Szsn4a%2BMOiXWp6uEEXKY5hAA1TVIyaeAmmaH2RyhofjJzhGfgrjaq662foWNYroPBxgl4OVf18J-2IED-mnxWvf7YVqetuPkrYBwABxXBAbA0QKDC%2Bt8-Zb0WuTUsGVx4R21IIV6McNYFwRJGfi0AADWkZkyYNwDUCkjBjgpiAiqFmbkpAeVqgHUm29boU2kvvSenBBDox2JaG0qDcAdmRGXRAZVPqMAaOeFSBxSIpwzlIRKMNkrZzodA%2Bc4dkbwLpjsFStpmiMFPowc%2BQ5TgaLPMseM-VYD7EODgM8F9BKeRJrDYeO8mIKNgUox2StVEi3TIwCxcw2wtDERRVg-CmhCIvhIyQlCIHB2fP5RxsoJ6RwgLQBSSD86ClhCmBU8AFjAVgGDFo7DC5WKoQ-GhkCR7RIes4yQtBo6SEgIA9MDRUxHCWAAaUQIgfApjkQ4H2NghY2jfYUOohEqBDiKkOyqTXHYaD%2BkYMFDUAqRUDiWkgogNWyDC6AJBmDCC1UczSOurIm28jxnv04LQGetTIxJnsnwpu0BWCNLNBpeAu5BFDjKtAECf1LGXmGVdBq1tn53QYW-SuXBaBH1qfUx5TTzGYAZIVZYkEnT4AZEMJkfyhIjLKVAMesS4FSFoJ-WpbSOk9WTv46kMzGBzIRKE56fB773BKZE5qoLFETO4LQRBtTEXORwBCBAQohnYoBY8aodwrgTBqMaMG7RwmPCAA)

#### Code

```fsharp
    let ppm = "P3\n\
               10 2\n\
               255\n\
               255 204 153 255 204 153 255 204 153 255 204 153 255 204 153 255 204\n\
               153 255 204 153 255 204 153 255 204 153 255 204 153\n\
               255 204 153 255 204 153 255 204 153 255 204 153 255 204 153 255 204\n\
               153 255 204 153 255 204 153 255 204 153 255 204 153\n"
```
            

#### Result

```fsharp
let ppm =
    "P3\n\
               10 2\n\
               255\n\
               255 204 153 255 204 153 255 204 153 255 204 153 255 204 153 255 204\n\
               153 255 204 153 255 204 153 255 204 153 255 204 153\n\
               255 204 153 255 204 153 255 204 153 255 204 153 255 204 153 255 204\n\
               153 255 204 153 255 204 153 255 204 153 255 204 153\n"

```
            
#### Problem description

I am trying out Fantomas for the first time on my codebases, trying to decide if I would like to use it. However, I did see this particular case where the formatter clearly gets something wrong. I have not dived into it too much to figure out what is the particular feature here that's throwing it off, but multiline strings are a specific feature of F# that allows you to end a string with `\` such that the next non-whitespace character in the newline is immediately concatenated to the string immediately to the left of the `\`. [See the documentation of this feature here.](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/strings#triple-quoted-strings)

My total guess would be that Fantomas is not taking into account the special behavior of `\` when at the end of a line.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2022-10-26T10:57:39Z - 5c54a3907483ea4936d456a69741537ad9c6026c

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment] 2022-10-27 07:40
Hello, could you please elaborate on what the problem is here? I do believe the formatted string is equivalent to the input.

Fantomas will take the original string text straight out of the source code. As you can see all `\` are still present, so I'm not really sure what you are referring to.

Your original code does have a *[vanity alignment](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#avoid-formatting-that-is-sensitive-to-name-length)*.
You added a bunch of spaces before `10 2\n\` to align with the name which is not advised in the first place. Notice that the exact amount of spaces was restored on the second line + 4 additional spaces for the indentation. (A [sample ](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAHXAtmALwA6ATqQHYQSmQAKAzKdaxdbRAIwAMYAJlZV2lGlwEBWScNGcJ0wbwAsYbpKaDFAlWo1bJS1es1TDO4-rNG9p7StmsxXWwZsm3F19a8efuk0cOcVp-SztzAKt7cM8oiPdoyOUg5y4-GO9MjOSs3MC2SGDgzBx8ImIwemZU%2BVo%2BQVqQiDMmlzC8xITfJK642LC29N6e7vj%2BztGh0OyR8Y6cvoW5lLYnOp4VyfnZsfDZSEgAGnAoAGdsLABLKgBzM9QwAG1TiFAXKAASLABPXGQ0JAblhjq9aJBPgA3ACG6AArgDnmCuLwTh8IJAAJJUJBULAAZSuAC9kGj0cpkWAALpggC%2BZLelIhv3%2BjyBeNBHwhMPhiJe6LUDJckAAstCAB4AGRuiEliDuWAAFpz0dwdJSaVx6WD3sLvn9EZB5fAAPIAM2lVEQ%2BN%2BmBVXG5sIRj356IEQodAFEcebLaTKRj0GbIBq6ULdQ79azAQAjWCwdD28FQp18gNgJge8HYi7kLAAMRusIAcogAO7oGVJrhYcgI0Na8NMqOGuMJ6tfHnOtCuj7KLMY-G4aHQRAAIUQZtg5EQDGh5GhBGwiHIHYgtfrH01tG1XAjyZZrfjiazjt5LvTkgHUCHI-Hk%2BnstgZZX0GhF2xkNgb%2BusCoa7ADdEAbHcmy5Fs2TbE9my7NMBQANmvSBb1HCcpxnABVfBX3fRBP2-aFf3-a8zVhC4QIgXdaH3DEINjY8OzPbskQFAB2JCUPvdDEAAYXQd8zh4v8zg3aAsGnADSPQcitzDHVm0PSCGNPFNzx7dMAA4OOHVCHxnEVEAIGMV0ksjgNkxt5PAxT6PbFTYIvAUAE5tLvNDHyE9A-1M6TzJcbdKLAvUbKgKDGNU5jexcPhXNHABBM0sBXISCAIaEAKAiiwCoxlrINJS7Jg1NHNVbhYq4x98UMq44C84j0ykmT-LkvcFPy2zoPAhz1IFNVyoSpLyCqggaoTbzr0yizQKs4L2tC5SirUljVUzdNkJ0xA4vIWA4RxAARRBKxGwaMrrPyuAC7KgsjEL2RBezip61V%2BzWsVxUxM0ABVFXlfFFWnLAAHUrngJUAN4LKcrAGivlu4Fwu65aPnUJC3o%2B775U9Xy-oB4HQeVa94IhqbApmm65ruhHHqR6LENeiVsTNK5xRNf4F3E8hPXFXAZzOM4rnGzTieayzWry6MoHhh6lqi9J2Pp8UACVEDgch4DxsHr2UYWLpa6i2olynpci9NuC0hXldV%2BBizhIyV3NTEkoIB5r24SHroPCmCDhdBrkrK182nNKsEGz78uNuDVRctbLeneARR9v2ZUD8hg5OpDoEVecR0GgB9MsQbB92yc9w2pcWk2BR0VGJS2hcfhNchpREjWCaF4uxdmsuOQjkqPgEMqFbr6EG6bq4RJtu3yAdp2XdNjv9fFw1vd9q5-cQFO05XMPWV7p7%2B-dNbh9H5usAT1f183wj07WzPs7Eld88L5UF9yrvDXLrrqdl0JVoFUUJQADVUxjhuPAG4txW4AQ0jrWgl0oYw2ZBTT%2BepEY-xaC9f%2Bb18y7TEgLKgoCcQQKgVrWBEB4Ee1onDHuFdI79yvArPasAsAAHFsBcx5ogPm%2BCSHtxJldEuVCKZhT3jTCQdMsGJzXjKMcXloAAGsxwLgUdgM4JoqD4kXLxBMtt6oCkaudOBes37k0NiI2hfd2jy3-qWCsMjsAvnlDvRAB0mZUCuEROKOIDJTzngKSaItpqd1MUeQqX8ZbpgEObf%2BcVKy3CoDgqgeC-yEniYROEM5PqwGxLiLAhF8E%2BSarrUWi934FU6qg7%2BkTo4xN9iuKg%2BTIRPjuD44y5BXE3A8fgvx6IDGv2hgbUJFTIxoPTEwVEr0pF%2BklIuGM8BoR8VgPzO4tj16FMMeQ4xAyl7lKphEgUTBB7-w4SuK4S48SwgANKIEQLgHJ8osDYiUdCJJbd9FmX6Ygui80wmVP2eiJgh9-6yJefIv0Zwto7RxKWESiB45SPXhw3m-NhKnU3IE0mwTS5DL2ZXAFf90SQDHPOdyM49rj2gOQM5RYkrwAwu4v8B1oD8XZgUkiHz%2BEIMGbs0R6CMyYMJScql5y8noBtNtOEIk6y4BtD8O07LfKfO5YCFBIyqkHIYf-a5ty3qTzaeaEFVAwUyh6cjXgZDqRbK%2Bbdcx4S8UfCYBIwl4qapnwQP6d5irOWnCpGSIEZx8z80eH02kQA) of non-vanity alignment input.)

**Comment by bmitc** [comment] 2022-10-27 08:12
I expected:

```fsharp
let ppm =
    "P3\n\
     10 2\n\
     255\n\
     255 204 153 255 204 153 255 204 153 255 204 153 255 204 153 255 204\n\
     153 255 204 153 255 204 153 255 204 153 255 204 153\n\
     255 204 153 255 204 153 255 204 153 255 204 153 255 204 153 255 204\n\
     153 255 204 153 255 204 153 255 204 153 255 204 153\n"
```

I think (or at least thought that) the current behavior is clearly worse than what it started with. Because the alignment went from breaking a small rule of the style guide but consistent alignment to having a single compliant line followed by several lines of arbitrary alignment. They are arbitrary because of the loss of information after the format as to what those lines were aligned to.

If it isn't considered a bug, it isn't clear what rule it is following. Although the source input contained an alignment sensitive to the length of the binding name (I dislike calling it a vanity alignment), I think the formatter should adjust the remaining indentation similarly to the first line. Formatters are of course not constrained to just emitting equivalent expressions.

As far as I can tell, the entire point of the feature of ending a line with `\` is to support such indented left alignment of multiline strings, without inserting the whitespace into the string.

**Comment by nojaf** [comment] 2022-10-27 08:23
That would require us to check what is inside the string and that is a can of worms I'm not opening again. 
I'm closing this case as "bad input is badly formatted", there is no interest in having this addressed.

**Closed by nojaf** 2022-10-27 08:23 UTC
Labels: discussion

**Comment by bmitc** [comment] 2022-10-27 08:29
Just as a further point, it doesn't make much sense to me to have formatted code, run a formatter, and then have to go back and manually format things, as that breaks the goal of a formatter. The `\` is an explicit F# feature and should be supported.

**Comment by bmitc** [comment] 2022-10-27 08:35
Actually, it occurs to me now that the rule the formatter is following is arbitrary. The original source input does **_not_** break the rule you linked of being sensitive to the length of naming, because the string expression is not sensitive to indentation and alignment at all. By that logic, the formatter really should not take any action here, leaving the input alone.

**Comment by auduchinok** [comment] 2022-10-28 10:47
> As far as I can tell, the entire point of the feature of ending a line with \ is to support such indented left alignment of multiline strings, without inserting the whitespace into the string.

@nojaf I think this feature could be good to have support in the formatter, and it seems relatively straightforward to do. Maybe it could be an `up-for-grabs` or something like that?
