### ISSUE TITLE
Unicode null escapes are unescaped (v3.0.0. beta1, beta2)

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#464] opened 2019-08-14 18:52 UTC
### Description

The escape \u0000 is replaced by a literal NUL, making git detect the formatted file as binary.

### Repro code

This happens with 3.0.0 beta1 and carries through to beta 2, but using [the tool with the next-gen preview version](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=AQ4GwUwF2BbBDA1hAYgSzFCAnYAzDLbAYzHgGdzgAKADwC5gBlKbNAOwHMBKYAXgCwAKFChaAOgBKEAA5liEagHIAOgFcADFo1KANMFUql3YaJAAfAHzAAwgHtYCdgBMAMhwjiAavDBpn8FjSnBC0EOSmZlbMEACO4mhENASYOKQUVJbWXmjkiXbY4gBy8LCohDjk4gCCzs7cQA) causes that tool to fault instead.

The problem doesn't show with 2.9.2 or the 2.9.3-preview options

Input
```
    let makeFilter filterclass (x: String) =
      x.Replace('\u0000', '\\')
      |> CommandLine.ValidateRegexes
      |> Seq.iter (filterclass >> Visitor.NameFilters.Add)
```
to the 3.0.0 beta 2 tool replaces the character \u0000 with a NUL byte.  A NUL byte is also added to the end of the file.

**Comment by jindraivanek** [comment] 2019-08-15 08:13
Tool fault was caused by unrelated issue on tool side (incompatible version of FSharp.Compiler.Service and FSharp.Core), it is fixed now.

**Closed** 2019-08-30 08:00 UTC
